"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {getClientAuth} from "@/lib/firebase-client";

export default function ReviewPage({params}:{params:Promise<{orderId:string}>}){const [orderId,setOrderId]=useState("");const [targetId,setTargetId]=useState("");const [role,setRole]=useState<"buyer"|"seller">("buyer");const [rating,setRating]=useState(5);const [text,setText]=useState("");const [status,setStatus]=useState("Loading…");const [done,setDone]=useState(false);
useEffect(()=>{let cancelled=false;(async()=>{try{const {orderId:id}=await params;if(cancelled)return;setOrderId(id);const auth=getClientAuth();await auth.authStateReady();const user=auth.currentUser;if(!user){setStatus("Please sign in to leave a review for this order.");return}const token=await user.getIdToken();const buyerAttempt=await fetch(`/api/reviews?orderId=${encodeURIComponent(id)}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const buyerData=await buyerAttempt.json();if(buyerAttempt.ok){if(cancelled)return;if(buyerData.order.status!=="completed-released")throw new Error("Reviews are available after the order has been completed and released.");if(buyerData.reviewed){setDone(true);setStatus("You have already reviewed this order.");return}setRole("buyer");setTargetId(buyerData.order.sellerId);setStatus("");return}const sellerAttempt=await fetch(`/api/buyer-reviews?orderId=${encodeURIComponent(id)}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const sellerData=await sellerAttempt.json();if(!sellerAttempt.ok)throw new Error(sellerData.error||"Unable to load order");if(cancelled)return;if(sellerData.order.status!=="completed-released")throw new Error("Reviews are available after the order has been completed and released.");if(sellerData.reviewed){setDone(true);setStatus("You have already reviewed this buyer.");return}setRole("seller");setTargetId(sellerData.order.buyerId);setStatus("")}catch(e){if(!cancelled)setStatus(e instanceof Error?e.message:"Unable to load order")}})();return()=>{cancelled=true}},[params]);
async function submit(e:React.FormEvent){e.preventDefault();setStatus("Submitting…");try{const auth=getClientAuth();await auth.authStateReady();const user=auth.currentUser;if(!user)throw new Error("Please sign in again");const token=await user.getIdToken();const endpoint=role==="buyer"?"/api/reviews":"/api/buyer-reviews";const body=role==="buyer"?{orderId,sellerId:targetId,rating,text}:{orderId,buyerId:targetId,rating,text};const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to submit review");setDone(true);setStatus("Review submitted. Thank you!")}catch(e){setStatus(e instanceof Error?e.message:"Unable to submit review")}}
return <main style={{maxWidth:760,margin:"60px auto",padding:24,fontFamily:"inherit"}}><header style={{marginBottom:36}}><Link href="/" aria-label="Back to SaharaSnow" style={{display:"inline-flex",alignItems:"center",gap:10,textDecoration:"none",color:"inherit",fontWeight:800,fontSize:20}}><img src="/logo.png" alt="SaharaSnow" style={{width:42,height:42,objectFit:"contain"}}/><span>SAHARASNOW</span></Link></header><h1>{role==="buyer"?"Review your completed order":"Rate this buyer"}</h1>{done?<div><p>{status}</p><Link href="/" style={{display:"inline-flex",alignItems:"center",gap:10,marginTop:20,textDecoration:"none",fontWeight:700}}><img src="/logo.png" alt="SaharaSnow" style={{width:34,height:34,objectFit:"contain"}}/><span>Back to SaharaSnow</span></Link></div>:status?<p>{status}</p>:<form onSubmit={submit} style={{display:"grid",gap:20}}><div><p><b>Your rating</b></p><div style={{display:"flex",gap:8}}>{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} aria-label={`${n} stars`} style={{fontSize:32,border:0,background:"transparent",cursor:"pointer",opacity:n<=rating?1:.3}}>★</button>)}</div></div><label><b>{role==="buyer"?"Your review":"Your feedback about this buyer"}</b><textarea required minLength={5} maxLength={2000} rows={7} value={text} onChange={e=>setText(e.target.value)} placeholder={role==="buyer"?"Tell other buyers about your experience…":"Describe what it was like working with this buyer…"} style={{display:"block",width:"100%",marginTop:8,padding:12,borderRadius:10,border:"1px solid #ddd"}}/></label><button type="submit" style={{padding:"12px 18px",borderRadius:10,border:0,cursor:"pointer"}}>Submit review</button></form>}</main>}
