import {FieldValue} from "firebase-admin/firestore";
import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {db} from "@/lib/firebase-admin";
import {notifyAdminInApp,notifyUser} from "@/lib/notifications";
import {publicError,userFromRequest} from "@/lib/server";
export const runtime="nodejs";
const file=z.object({name:z.string().min(1).max(255),url:z.string().url().max(2000),size:z.number().int().positive().max(100*1024*1024),type:z.string().max(255).optional()});
const schema=z.object({orderId:z.string().min(1),message:z.string().trim().max(3000).default(""),attachments:z.array(file).min(1).max(10)});
export async function POST(req:NextRequest){try{const user=await userFromRequest(req),body=schema.parse(await req.json());const ref=db.collection("orders").doc(body.orderId),snap=await ref.get();if(!snap.exists)return NextResponse.json({error:"Order not found."},{status:404});const order=snap.data()||{};if(String(order.sellerId)!==user.uid)return NextResponse.json({error:"Only the seller can deliver this order."},{status:403});if(!["paid","in-progress"].includes(String(order.status)))return NextResponse.json({error:"This order is not ready for delivery."},{status:400});await ref.set({status:"delivered",delivery:{message:body.message,attachments:body.attachments,deliveredAt:FieldValue.serverTimestamp()},updatedAt:FieldValue.serverTimestamp()},{merge:true});await ref.collection("events").add({type:"delivery_submitted",message:body.message||`${body.attachments.length} delivery file(s) uploaded for review.`,attachments:body.attachments,actorId:user.uid,createdAt:FieldValue.serverTimestamp()});const number=String(order.orderNumber||body.orderId);await notifyUser({userId:String(order.buyerId),type:"order_delivered",eventId:body.orderId,title:`Order #${number} delivered`,message:`Your seller delivered ${body.attachments.length} file(s). Open the order to review the delivery.`,link:`/?order=${body.orderId}`,email:true});await notifyAdminInApp({type:"order_delivery",eventId:body.orderId,title:`Order #${number} delivered`,message:`Delivery files were uploaded and are available for administrator review.`,link:"/admin"});return NextResponse.json({ok:true});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
