import {FieldValue}from"firebase-admin/firestore";
import {NextRequest,NextResponse}from"next/server";
import {z}from"zod";
import {db}from"@/lib/firebase-admin";
import {notifyAdminInApp,notifyUser}from"@/lib/notifications";
import {postSystemMessage}from"@/lib/messaging";
import {publicError,userFromRequest}from"@/lib/server";
export const runtime="nodejs";
const file=z.object({name:z.string().min(1).max(255),url:z.string().url().max(2000),size:z.number().int().positive().max(100*1024*1024),type:z.string().max(255).optional()});
const schema=z.object({orderId:z.string().min(1),message:z.string().trim().max(3000).default(""),attachments:z.array(file).max(10).default([])}).refine(v=>v.message.length>0||v.attachments.length>0,{message:"Add a delivery message or attach at least one file."});
export async function POST(req:NextRequest){try{const user=await userFromRequest(req),body=schema.parse(await req.json());const ref=db.collection("orders").doc(body.orderId);let order:any,reviewEnds:Date;await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw Error("Order not found.");order=snap.data()||{};if(String(order.sellerId)!==user.uid)throw Error("Only the seller can deliver this order.");if(!["paid","in-progress","crypto-received"].includes(String(order.status)))throw Error("This order is not ready for delivery.");const now=new Date(),deliveryDays=Math.max(1,Math.round(Number(order.packageDeliveryDays))||1);reviewEnds=new Date(now.getTime()+deliveryDays*24*60*60*1000);tx.set(ref,{status:"delivered",deliveryStatus:"delivered",delivery:{message:body.message,attachments:body.attachments,deliveredAt:FieldValue.serverTimestamp()},deliveredAt:FieldValue.serverTimestamp(),disputeWindowEndsAt:reviewEnds,disputeDeadline:reviewEnds,clearanceStartsAt:FieldValue.delete(),clearanceEndsAt:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp()},{merge:true});});await ref.collection("events").add({type:"delivery_submitted",message:body.message||`${body.attachments.length} delivery file(s) uploaded.`,attachments:body.attachments,actorId:user.uid,createdAt:FieldValue.serverTimestamp()});const number=String(order.orderNumber||body.orderId),deliveryDays=Math.max(1,Math.round(Number(order.packageDeliveryDays))||1),dayLabel=`${deliveryDays} day${deliveryDays===1?"":"s"}`;const deliverySummary=body.attachments.length?`Your seller delivered ${body.attachments.length} file(s).`:"Your seller marked this order as delivered.";await notifyUser({userId:String(order.buyerId),type:"order_delivered",eventId:`${body.orderId}_delivered`,title:`Order #${number} delivered`,message:`${deliverySummary} You have ${dayLabel} to review and dispute before the order enters the five-day clearance period.`,link:`/?order=${body.orderId}`,email:true});await notifyAdminInApp({type:"order_delivery",eventId:body.orderId,title:`Order #${number} delivered`,message:`The ${dayLabel} buyer review window has started, followed by the standard five-day clearance.`,link:"/admin"});const buyerId=String(order.buyerId||"");if(buyerId)await postSystemMessage({buyerId,sellerId:user.uid,orderId:body.orderId,text:body.message?`📦 Order #${number} delivered: ${body.message}`:`📦 Order #${number} delivered. You have ${dayLabel} to review and dispute before the five-day clearance period begins.`,attachments:body.attachments});return NextResponse.json({ok:true,orderId:body.orderId,orderNumber:number,status:"delivered",disputeWindowEndsAt:reviewEnds!.toISOString()});}catch(e){const x=e instanceof z.ZodError?{message:"Invalid delivery request.",status:400}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
