"use client";
import { useEffect,useMemo,useState,type FormEvent } from "react";
import Link from "next/link";
import "./admin.css";

type Item=Record<string,unknown>&{id:string};
type Tab="kyc"|"listings"|"reviews"|"withdrawals"|"orders"|"tickets"|"users"|"earnings"|"reports"|"auditLogs";
type Data={adminEmail:string;kyc:Item[];listings:Item[];reviews:Item[];withdrawals:Item[];orders:Item[];tickets:Item[];users:Item[];earnings:Item[];auditLogs:Item[];reports:Item[]};
type Auth={getIdToken:(force?:boolean)=>Promise<string>};
const labels:Record<Tab,string>={kyc:"KYC",listings:"Listings",reviews:"Reviews",withdrawals:"Withdrawals",orders:"Orders & disputes",tickets:"Support",users:"Users",earnings:"Earnings",reports:"Reports",auditLogs:"Audit log"};
const tabs=Object.keys(labels) as Tab[];
const PAGE_SIZE=30;
const money=(v:unknown)=>`$${(Number(v||0)/100).toFixed(2)}`;
const txt=(v:unknown)=>v===undefined||v===null||v===""?"—":typeof v==="object"?JSON.stringify(v):String(v);
const listingMoney=(item:Item)=>{const cents=item.priceCents??item.startingPriceCents??item.amountCents;const raw=item.price??item.startingPrice??item.amount;if(cents!==undefined&&cents!==null)return money(cents);if(raw===undefined||raw===null||raw==="")return"—";const n=Number(raw);return Number.isFinite(n)?`$${n.toFixed(2)}`:txt(raw)};
const dateValue=(value:unknown):Date|null=>{if(!value)return null;if(value instanceof Date)return value;if(typeof value==="string"||typeof value==="number"){const d=new Date(value);return Number.isNaN(d.getTime())?null:d;}if(value&&typeof value==="object"&&"seconds" in value){const seconds=Number((value as {seconds?:unknown}).seconds);const d=new Date(seconds*1000);return Number.isNaN(d.getTime())?null:d;}return null;};
const dateTime=(value:unknown)=>{const d=dateValue(value);return d?new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(d):"—";};
const timestampKeys=(item:Item)=>Object.entries(item).filter(([k,v])=>/(^|_)(created|updated|reviewed|processed|submitted|paid|released|completed|deleted|published|joined|requested|expires?|date|time)(At|Date|Time)?$/i.test(k)&&dateValue(v)).map(([k,v])=>`${k.replace(/([A-Z])/g," $1")}: ${dateTime(v)}`);
const newest=(item:Item)=>{for(const key of ["updatedAt","submittedAt","createdAt","reviewedAt","timestamp"]){const d=dateValue(item[key]);if(d)return d.getTime();}return 0;};
function urls(value:unknown,path="document"): {name:string;url:string}[]{if(typeof value==="string"&&/^https?:\/\//.test(value))return[{name:path,url:value}];if(Array.isArray(value))return value.flatMap((x,i)=>urls(x,`${path} ${i+1}`));if(value&&typeof value==="object")return Object.entries(value as Record<string,unknown>).flatMap(([k,v])=>urls(v,k));return[];}
const userIdFor=(item:Item)=>String(item.userId||item.uid||item.ownerId||item.id||"");
const fullName=(item:Item)=>[item.firstName,item.lastName].filter(v=>typeof v==="string"&&v.trim()).join(" ")||String(item.name||item.displayName||"");
const cryptoAmount=(cents:unknown,currency:string)=>`${(Number(cents||0)/100).toFixed(2)} ${currency}`;

export default function AdminPage(){
 const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<Tab>("listings");const[auth,setAuth]=useState<Auth|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[search,setSearch]=useState("");const[page,setPage]=useState(1);
 const load=async(u:Auth)=>{setError("");try{const token=await u.getIdToken(true);const[h,r]=await Promise.all([fetch("/api/admin",{headers:{authorization:`Bearer ${token}`},cache:"no-store"}),fetch("/api/admin/reviews",{headers:{authorization:`Bearer ${token}`},cache:"no-store"})]);const a=await h.json();const rr=await r.json();if(!h.ok)throw new Error(a.error||"Unable to load admin dashboard.");setData({adminEmail:String(a.adminEmail||""),kyc:a.kyc||[],listings:a.listings||[],reviews:rr.reviews||[],withdrawals:a.withdrawals||[],orders:a.orders||[],tickets:a.tickets||[],users:a.users||[],earnings:a.earnings||[],auditLogs:a.auditLogs||[],reports:a.reports||[]});}catch(e){setError(e instanceof Error?e.message:"Unable to load admin dashboard.");}};
 useEffect(()=>{let off:(()=>void)|undefined;(async()=>{try{const[{getClientAuth},fa]=await Promise.all([import("@/lib/firebase-client"),import("firebase/auth")]);off=fa.onAuthStateChanged(getClientAuth(),u=>{if(u){const x:Auth={getIdToken:f=>u.getIdToken(f)};setAuth(x);void load(x);}else setError("Sign in with your administrator account first.");});}catch(e){setError(e instanceof Error?e.message:"Unable to initialize admin.");}})();return()=>off?.();},[]);
 const rows=useMemo(()=>{const all=[...(data?.[tab]||[])];const q=search.trim().toLowerCase();const filtered=q?all.filter(x=>JSON.stringify(x).toLowerCase().includes(q)):all;return tab==="kyc"?filtered.sort((a,b)=>newest(b)-newest(a)):filtered;},[data,tab,search]);
 const totalPages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));
 const safePage=Math.min(page,totalPages);
 const pageRows=rows.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE);
 const pager=totalPages>1?<div className="adminPagination"><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,Math.min(p,totalPages)-1))}>← Prev</button><span>Page {safePage} of {totalPages}</span><button disabled={safePage>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,Math.min(p,totalPages)+1))}>Next →</button></div>:null;
 const users=useMemo(()=>new Map((data?.users||[]).map(u=>[u.id,u])),[data]);
 const patch=async(item:Item,resource:string,action:string,noteRequired=false)=>{if(!auth)return;const note=window.prompt(noteRequired?"Enter the reason:":"Optional admin note:");if(note===null||(noteRequired&&!note.trim()))return;setBusy(`${item.id}:${action}`);try{const token=await auth.getIdToken(true);const endpoint=resource==="listing"&&(action==="approve"||action==="reject")?"/api/admin/listing-review":"/api/admin";const res=await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({resource,id:item.id,action,note:note.trim()})});const out=await res.json();if(!res.ok)throw new Error(out.error||"Admin action failed.");await load(auth);}catch(e){setError(e instanceof Error?e.message:"Admin action failed.");}finally{setBusy("");}};
 const reviewAction=async(item:Item,action:"delete"|"reset")=>{if(!auth)return;if(action==="delete"&&!window.confirm("Delete this review permanently?"))return;const note=window.prompt(action==="reset"?"Why should the buyer submit a new review?":"Optional admin note:");if(note===null||(action==="reset"&&!note.trim()))return;setBusy(`${item.id}:${action}`);try{const token=await auth.getIdToken(true);const res=await fetch("/api/admin/reviews",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({reviewId:item.id,action,note:note.trim()})});const out=await res.json();if(!res.ok)throw new Error(out.error||"Review action failed.");await load(auth);}catch(e){setError(e instanceof Error?e.message:"Review action failed.");}finally{setBusy("");}};
 const resolveDispute=async(item:Item,e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!auth)return;const form=e.currentTarget;const sellerAmount=Number((form.elements.namedItem("sellerAmount") as HTMLInputElement).value||0);const buyerAmount=Number((form.elements.namedItem("buyerAmount") as HTMLInputElement).value||0);const note=(form.elements.namedItem("note") as HTMLInputElement).value.trim();if(!note){setError("Enter a resolution note explaining the split.");return}setBusy(`${item.id}:resolve`);try{const token=await auth.getIdToken(true);const res=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({resource:"order",id:item.id,action:"resolve",note,sellerAmount,buyerAmount})});const out=await res.json();if(!res.ok)throw new Error(out.error||"Unable to resolve dispute.");await load(auth);}catch(err){setError(err instanceof Error?err.message:"Unable to resolve dispute.");}finally{setBusy("");}};
 const clearAudit=async()=>{if(!auth||!window.confirm("Clear the entire audit log? This cannot be undone."))return;setBusy("audit:clear");try{const token=await auth.getIdToken(true);const res=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({resource:"auditLogs",id:"all",action:"clearAll"})});if(!res.ok)throw new Error((await res.json()).error||"Unable to clear audit log.");await load(auth);}catch(e){setError(e instanceof Error?e.message:"Unable to clear audit log.");}finally{setBusy("");}};
 const earningsTotals=rows.reduce((a,x)=>({released:a.released+Number(x.totalEarningsCents||x.totalReleasedCents||x.releasedCents||0),pending:a.pending+Number(x.pendingEarningsCents||x.pendingCents||0),available:a.available+Number(x.availableBalanceCents||x.availableCents||0)}),{released:0,pending:0,available:0});
 const times=(item:Item)=><small style={{display:"block",marginTop:6,lineHeight:1.6}}>{timestampKeys(item).length?timestampKeys(item).join(" · "):"Date & time: —"}</small>;
 return <main className="adminShell"><header className="adminHeader"><Link href="/" className="brand">saharasnow</Link><div><b>Admin control centre</b><small>{data?.adminEmail||"Secure administrator access"}</small></div><div className="adminHeaderActions"><button onClick={()=>auth&&void load(auth)}>Refresh</button></div></header><section className="adminHero"><div><span>LIVE OPERATIONS</span><h1>Marketplace administration</h1><p>Manage trust, services, reviews, earnings and marketplace records.</p></div></section>{error&&<div className="adminError">{error}</div>}<nav className="adminTabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>{setTab(t);setSearch("");setPage(1);}}>{labels[t]} <span>{data?.[t]?.length||0}</span></button>)}</nav><section className="adminPanel"><div className="adminPanelHead"><div><h2>{labels[tab]}</h2><p>{rows.length} record{rows.length===1?"":"s"}</p></div><div style={{display:"flex",gap:8}}>{tab==="auditLogs"&&<button className="danger" disabled={busy==="audit:clear"} onClick={()=>void clearAudit()}>Clear everything</button>}<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search this section…" /></div></div>{pager}
 {tab==="earnings"&&<><div className="earningsSummary"><div><span>Released</span><strong>{money(earningsTotals.released)}</strong></div><div><span>Pending</span><strong>{money(earningsTotals.pending)}</strong></div><div><span>Available</span><strong>{money(earningsTotals.available)}</strong></div></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>User</th><th>Email</th><th>Released</th><th>Pending</th><th>Available</th><th>Withdrawn</th><th>Updated date & time</th></tr></thead><tbody>{pageRows.map(x=>{const u=users.get(x.id)||x;return <tr key={x.id}><td>{txt(fullName(x)||fullName(u)||x.id)}</td><td>{txt(x.email||u.email)}</td><td>{money(x.totalEarningsCents||x.totalReleasedCents||x.releasedCents)}</td><td>{money(x.pendingEarningsCents||x.pendingCents)}</td><td>{money(x.availableBalanceCents||x.availableCents)}</td><td>{money(x.withdrawnCents)}</td><td>{dateTime(x.updatedAt||x.createdAt||u.updatedAt||u.createdAt)}</td></tr>;})}</tbody></table></div></>}
 {tab!=="earnings"&&(rows.length===0?<div className="adminEmpty">No records found.</div>:<div className="adminRows">{pageRows.map(item=>{if(tab==="reviews")return <article className="adminRow" key={item.id}><div className="adminRowMain"><strong>⭐ {txt(item.rating)}/5 — {txt(item.reviewerName||item.buyerName||item.buyerId)}</strong><small>Seller: {txt(item.sellerId)} · Order: {txt(item.orderId)}</small><p>{txt(item.text||item.comment)}</p>{times(item)}</div><div className="adminRowActions"><button className="danger" disabled={busy===`${item.id}:delete`} onClick={()=>void reviewAction(item,"delete")}>Delete review</button><button disabled={busy===`${item.id}:reset`} onClick={()=>void reviewAction(item,"reset")}>Request new review</button></div></article>;
 if(tab==="kyc"){const uid=userIdFor(item);const u=users.get(uid)||{} as Item;const name=fullName(item)||fullName(u)||String(item.name||u.name||item.email||u.email||uid||item.id);const email=String(item.email||u.email||"—");const pic=[item.photoURL,item.profilePhoto,item.profileImage,item.avatarUrl,u.photoURL,u.profilePhoto,u.profileImage,u.avatarUrl].find(v=>typeof v==="string"&&/^https?:\/\//.test(v as string));const docs=urls(item).filter(d=>/document|id|passport|selfie|proof|upload|file|front|back|identity|license/i.test(d.name));const uniqueDocs=Array.from(new Map(docs.map(d=>[d.url,d])).values());return <article className="adminRow" key={item.id}><div className="adminRowMain"><div style={{display:"flex",alignItems:"center",gap:14}}>{typeof pic==="string"?<img src={pic} alt={`${name} profile`} width={62} height={62} style={{borderRadius:"50%",objectFit:"cover",border:"1px solid #d8ddea"}}/>:<div style={{width:62,height:62,borderRadius:"50%",background:"#e9ecf7",display:"grid",placeItems:"center",fontSize:26}}>👤</div>}<div><strong>{name}</strong><small style={{display:"block",marginTop:4}}>{email}</small><small style={{display:"block",marginTop:4}}>Status: {txt(item.status)}</small></div></div><p style={{marginTop:12}}>{item.reviewNote?`Review note: ${txt(item.reviewNote)}`:"Awaiting administrator review."}</p><div style={{marginTop:10}}><b>Latest KYC date & exact time: </b>{dateTime(item.updatedAt||item.submittedAt||item.createdAt||item.reviewedAt)}</div>{times(item)}<div style={{marginTop:12}}><b>Verification documents ({uniqueDocs.length})</b>{uniqueDocs.length>0?<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{uniqueDocs.map((d,i)=><a key={i} href={d.url} target="_blank" rel="noreferrer"><button>⬇ Download {d.name}</button></a>)}</div>:<p style={{marginTop:6}}>No downloadable verification documents were found on this KYC record.</p>}</div></div><div className="adminRowActions"><button onClick={()=>void patch(item,"kyc","approve")}>Approve</button><button onClick={()=>void patch(item,"kyc","reupload",true)}>Request new documents</button><button className="danger" onClick={()=>void patch(item,"kyc","reject")}>Reject</button></div></article>}
 if(tab==="listings"){const seller=users.get(String(item.sellerId||item.userId||item.ownerId||""));const sellerName=seller?fullName(seller)||txt(seller.name||seller.displayName):txt(item.sellerName||item.ownerName||item.sellerId||item.userId);const sellerEmail=seller?.email||item.email||item.sellerEmail||item.ownerEmail;const pic=seller&&(seller.photoURL||seller.profileImage||seller.avatarUrl);const description=item.description||item.longDescription||item.details||item.summary;const pendingEdit=item.pendingEditStatus==="pending-approval";const pending=item.pendingEdit&&typeof item.pendingEdit==="object"?item.pendingEdit as Record<string,unknown>:null;const pendingPhotos=Array.isArray(pending?.photoUrls)?pending.photoUrls.length:0;const pendingVideo=typeof pending?.videoUrl==="string"&&Boolean(pending.videoUrl);return <article className="adminRow" key={item.id} style={pendingEdit?{border:"2px solid #d92d20",background:"#fff6f5",boxShadow:"0 0 0 3px rgba(217,45,32,.08)"}:undefined}><div className="adminRowMain"><div style={{display:"flex",alignItems:"center",gap:10}}>{typeof pic==="string"?<img src={pic} alt="" width={44} height={44} style={{borderRadius:"50%",objectFit:"cover"}}/>:<div style={{width:44,height:44,borderRadius:"50%",background:"#e9ecf7",display:"grid",placeItems:"center"}}>👤</div>}<div><strong>{txt(item.title)}</strong><small>Created by: {sellerName} · {txt(sellerEmail)}</small></div></div>{pendingEdit&&<div style={{marginTop:12,padding:"10px 12px",borderRadius:10,background:"#d92d20",color:"#fff",fontWeight:800}}>🔴 EDITING — WAITING FOR APPROVAL AGAIN</div>}<div className="listingDetails"><div className="detailLine"><b>Description</b><span className="listingDescription">{txt(description)}</span></div><div className="detailLine"><b>Price</b><span className="listingPrice">From {listingMoney(item)}</span></div><div className="detailLine"><b>Seller</b><span>{sellerName} · {txt(sellerEmail)}</span></div><div className="detailLine"><b>Status / category</b><span>{txt(item.status)} · {txt(item.category)}{item.subcategory?` · ${txt(item.subcategory)}`:""}</span></div>{pendingEdit&&<div className="detailLine"><b>Pending changes</b><span>{pendingPhotos} image{pendingPhotos===1?"":"s"}{pendingVideo?" + video/YouTube":""} · submitted {dateTime(item.pendingEditSubmittedAt)}</span></div>}</div>{times(item)}</div><div className="adminRowActions"><button onClick={()=>void patch(item,"listing","approve")} disabled={busy===`${item.id}:approve`}>{pendingEdit?"Approve edited listing":"Publish"}</button><button className="danger" onClick={()=>void patch(item,"listing","reject")} disabled={busy===`${item.id}:reject`}>{pendingEdit?"Reject edits":"Reject"}</button><button className="danger" onClick={()=>void patch(item,"listing","delete")} disabled={busy===`${item.id}:delete`}>Delete</button></div></article>}
 if(tab==="orders"&&item.status==="disputed"){const currency=txt(item.paymentCurrency||"USDT");const totalAmount=(Number(item.serviceCents||0)/100).toFixed(2);return <article className="adminRow disputeRow" key={item.id}><div className="adminRowMain"><strong>⚖️ Dispute — Order #{txt(item.orderNumber||item.id)}</strong><small>Total paid: {totalAmount} {currency} · Buyer: {txt(item.buyerId)} · Seller: {txt(item.sellerId)}</small><p>{txt(item.disputeReason)}</p>{times(item)}</div><form className="disputeResolveForm" onSubmit={e=>void resolveDispute(item,e)}><label>To seller ({currency})<input name="sellerAmount" type="number" step="0.01" min="0" max={totalAmount} defaultValue={totalAmount}/></label><label>To buyer ({currency})<input name="buyerAmount" type="number" step="0.01" min="0" max={totalAmount} defaultValue="0"/></label><label className="disputeNoteLabel">Resolution note<input name="note" type="text" placeholder="Explain the decision" required/></label><div className="disputeResolveActions"><button type="submit" disabled={busy===`${item.id}:resolve`}>{busy===`${item.id}:resolve`?"Resolving…":"Resolve dispute"}</button><button type="button" className="danger" disabled={busy===`${item.id}:delete`} onClick={()=>void patch(item,"order","delete")}>Delete</button></div></form></article>}
 if(tab==="withdrawals"){const currency=String(item.currency||"USDT").toUpperCase();const firstName=String(item.sellerFirstName||"").trim();const lastName=String(item.sellerLastName||"").trim();const name=[firstName,lastName].filter(Boolean).join(" ")||txt(item.sellerEmail||item.sellerId);const pic=typeof item.sellerProfileImageUrl==="string"&&item.sellerProfileImageUrl?item.sellerProfileImageUrl:"";const network=txt(item.payoutNetwork);const address=txt(item.payoutAddress);const status=String(item.status||"");const statusLabel=status==="paid-manually"?"✅ Paid":status==="rejected"?"❌ Rejected":"⏳ Pending manual payment";return <article className="adminRow" key={item.id}><div className="adminRowMain"><div style={{display:"flex",alignItems:"center",gap:12}}>{pic?<img src={pic} alt={`${name} profile`} width={50} height={50} style={{borderRadius:"50%",objectFit:"cover",border:"1px solid #d8ddea",flexShrink:0}}/>:<div style={{width:50,height:50,borderRadius:"50%",background:"#e9ecf7",display:"grid",placeItems:"center",fontSize:22,flexShrink:0}}>👤</div>}<div><strong>{name}</strong><small style={{display:"block",marginTop:2}}>{txt(item.sellerEmail)}</small><small style={{display:"block",marginTop:2}}>{statusLabel}</small></div></div><div className="listingDetails" style={{marginTop:12}}><div className="detailLine"><b>Currency & amount</b><span>{currency} · Gross {cryptoAmount(item.grossCents,currency)} · Fee {cryptoAmount(item.feeCents,currency)} · Net payout {cryptoAmount(item.netCents,currency)}</span></div><div className="detailLine"><b>Payout network</b><span>{currency} — {network}</span></div><div className="detailLine"><b>Wallet address</b><span style={{wordBreak:"break-all"}}>{address}</span></div><div className="detailLine"><b>Requested</b><span>{dateTime(item.requestedAt)}</span></div>{item.processedAt!==undefined&&<div className="detailLine"><b>Processed</b><span>{dateTime(item.processedAt)}{item.processedBy?` · by ${txt(item.processedBy)}`:""}</span></div>}{item.adminNote?<div className="detailLine"><b>Admin note</b><span>{txt(item.adminNote)}</span></div>:null}</div>{times(item)}</div><div className="adminRowActions">{status==="pending-manual-payment"&&<><button disabled={busy===`${item.id}:paid`} onClick={()=>void patch(item,"withdrawal","paid")}>Mark paid</button><button className="danger" disabled={busy===`${item.id}:reject`} onClick={()=>void patch(item,"withdrawal","reject",true)}>Reject & restore</button></>}</div></article>}
 const resource=tab==="orders"?"order":tab==="tickets"?"ticket":tab==="users"?"user":tab==="reports"?"report":"";const acts:[string,string][]=tab==="orders"?[["Release","release"],["Refund","refund"],["Delete","delete"]]:tab==="tickets"?[["Close","close"]]:tab==="users"?[["Restore","restore"],["Suspend","suspend"],["Reset phone","resetPhone"],["Restore KYC","restoreKyc"]]:tab==="reports"?[["Delete","delete"]]:[];return <article className="adminRow" key={item.id}><div className="adminRowMain"><strong>{txt(item.title||fullName(item)||item.name||item.subject||item.orderNumber||item.email||item.id)}</strong><small>{txt(item.email||item.status||item.category||item.createdAt)}</small><p>{txt(item.description||item.reason||item.message||item.note)}</p>{times(item)}</div><div className="adminRowActions">{acts.map(([label,action])=><button key={action} className={/reject|refund|delete|suspend/i.test(action)?"danger":""} disabled={busy===`${item.id}:${action}`} onClick={()=>void patch(item,resource,action,/reject|refund/i.test(action))}>{label}</button>)}</div></article>;})}</div>)}{pager}</section></main>}
