import { FieldValue } from "firebase-admin/firestore";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/firebase-admin";
import { publicError, userFromRequest } from "@/lib/server";
import { notifyUser } from "@/lib/notifications";

const ADMIN_EMAIL=(process.env.SUPER_ADMIN_EMAIL||"yiorgosantoni@gmail.com").toLowerCase();
const actionSchema=z.object({id:z.string().min(1).max(200),action:z.enum(["approve","reject"]),note:z.string().trim().max(500).optional()});
async function admin(req:NextRequest){const user=await userFromRequest(req);if((user.email||"").toLowerCase()!==ADMIN_EMAIL)throw new Error("ADMIN_FORBIDDEN");return user;}
function json(value:unknown):unknown{if(value&&typeof value==="object"&&"toDate" in value&&typeof (value as {toDate?:unknown}).toDate==="function")return (value as {toDate:()=>Date}).toDate().toISOString();if(Array.isArray(value))return value.map(json);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,json(v)]));return value;}
export async function GET(req:NextRequest){try{await admin(req);const snap=await db.collection("listings").where("pendingEditStatus","==","pending-approval").limit(100).get();return NextResponse.json({edits:snap.docs.map(d=>json({id:d.id,...d.data()}))});}catch(e){const x=e instanceof Error&&e.message==="ADMIN_FORBIDDEN"?{message:"Only the SaharaSnow administrator can access listing edits.",status:403}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PATCH(req:NextRequest){try{const actingAdmin=await admin(req),body=actionSchema.parse(await req.json()),ref=db.collection("listings").doc(body.id);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Listing not found.");const current=snap.data()||{};if(current.pendingEditStatus!=="pending-approval"||!current.pendingEdit)throw new Error("There is no pending listing edit to review.");const pending=current.pendingEdit as Record<string,unknown>;if(body.action==="approve"){tx.set(ref,{...pending,pendingEdit:FieldValue.delete(),pendingEditStatus:FieldValue.delete(),pendingEditSubmittedAt:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp(),moderationNote:body.note||"",moderatedBy:actingAdmin.email,moderatedAt:FieldValue.serverTimestamp()},{merge:true});}else{tx.set(ref,{pendingEdit:FieldValue.delete(),pendingEditStatus:"rejected",pendingEditSubmittedAt:FieldValue.delete(),lastEditRejectionNote:body.note||"",lastEditRejectedBy:actingAdmin.email,lastEditRejectedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});}});const updated=(await ref.get()).data()||{};if(updated.sellerId)await notifyUser({userId:String(updated.sellerId),type:body.action==="approve"?"listing_edit_approved":"listing_edit_rejected",eventId:`${body.id}_${body.action}`,title:body.action==="approve"?"Listing changes approved":"Listing changes rejected",message:body.action==="approve"?"Your listing changes were approved and are now live.":`Your listing changes were not approved${body.note?`: ${body.note}`:"."}`,link:"/?services=1",email:true});await db.collection("auditLogs").add({adminUid:actingAdmin.uid,adminEmail:actingAdmin.email,resource:"listing",resourceId:body.id,action:`seller-edit-${body.action}`,note:body.note||"",createdAt:FieldValue.serverTimestamp()});return NextResponse.json({ok:true});}catch(e){const x=e instanceof Error&&e.message==="ADMIN_FORBIDDEN"?{message:"Only the SaharaSnow administrator can review listing edits.",status:403}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
