"use client";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {getDownloadURL,ref,uploadBytesResumable} from "firebase/storage";
import {getClientAuth,getClientStorage} from "@/lib/firebase-client";
import styles from "./contact.module.css";

export default function ContactSeller({recipientId,sellerName}:{recipientId:string;sellerName:string}){
  const [signedIn,setSignedIn]=useState(false),[open,setOpen]=useState(false),[text,setText]=useState(""),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  useEffect(()=>onAuthStateChanged(getClientAuth(),user=>setSignedIn(Boolean(user))),[]);
  const start=()=>{if(!signedIn){sessionStorage.setItem("saharasnow_return_to",window.location.pathname);window.location.href="/?signin=1";return}setNotice("");setOpen(true)};
  const send=async()=>{const user=getClientAuth().currentUser;if(!user){setNotice("Please sign in first.");return}if(!text.trim()&&!files.length){setNotice("Write a message or attach at least one file.");return}if(files.some(file=>file.size<=0||file.size>100*1024*1024)){setNotice("Each attachment must be smaller than 100 MB.");return}setBusy(true);setNotice("");try{const conversationId=[user.uid,recipientId].sort().join("_");const attachments=[];for(let i=0;i<files.length;i++){const file=files[i],safeName=file.name.replace(/[^a-zA-Z0-9._()\- ]/g,"_").slice(0,180)||`file-${i+1}`,path=`messages/${conversationId}/${user.uid}/${Date.now()}-${crypto.randomUUID()}-${safeName}`;const uploaded=await new Promise<{name:string;url:string;size:number;type:string;path:string}>((resolve,reject)=>{const task=uploadBytesResumable(ref(getClientStorage(),path),file,{contentType:file.type||"application/octet-stream"});task.on("state_changed",undefined,reject,async()=>{try{resolve({name:file.name,url:await getDownloadURL(task.snapshot.ref),size:file.size,type:file.type||"application/octet-stream",path})}catch(error){reject(error)}})});attachments.push(uploaded)}const token=await user.getIdToken(true);const response=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({recipientId,text:text.trim(),attachments})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to send message");setText("");setFiles([]);setNotice("Message sent. You can continue the conversation from your inbox.")}catch(error){setNotice(error instanceof Error?error.message:"Unable to send message")}finally{setBusy(false)}};
  return <><button className={styles.contact} type="button" onClick={start}>Contact me for any questions</button>{open&&<div className={styles.backdrop} onMouseDown={()=>setOpen(false)}><section className={styles.modal} onMouseDown={event=>event.stopPropagation()}><button className={styles.close} onClick={()=>setOpen(false)} aria-label="Close">×</button><small>CONTACT SELLER</small><h2>Message {sellerName}</h2><p>You may message this seller after approved KYC or after completing an order with them.</p><textarea value={text} onChange={event=>setText(event.target.value)} maxLength={4000} rows={6} placeholder="Ask a question about this service…"/><label className={styles.filePicker}>📎 Attach files<input type="file" multiple onChange={event=>{const chosen=[...(event.target.files||[])].slice(0,5);const oversized=chosen.find(file=>file.size>100*1024*1024);if(oversized){setNotice(`“${oversized.name}” is larger than 100 MB.`);return}setFiles(chosen);event.currentTarget.value=""}}/></label>{files.length>0&&<div className={styles.fileQueue}>{files.map(file=><span key={`${file.name}-${file.size}`}>📎 {file.name}<button type="button" onClick={()=>setFiles(items=>items.filter(x=>x!==file))}>×</button></span>)}</div>}<button className={styles.send} disabled={busy||(!text.trim()&&!files.length)} onClick={send}>{busy?"Sending…":"Send message"}</button>{notice&&<div className={styles.notice}>{notice}</div>}</section></div>}</>;
}
