"use client";
import {useEffect,useState} from "react";
import {onAuthStateChanged} from "firebase/auth";
import {getClientAuth} from "@/lib/firebase-client";

type Payment={orderId:string;amountCents:number;depositAddress:string;network:string};
export default function OrderButton({listingId,packageIndex=0,packageName}:{listingId:string;packageIndex?:number;packageName?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[authReady,setAuthReady]=useState(false),[signedIn,setSignedIn]=useState(false),[payment,setPayment]=useState<Payment|null>(null),[txHash,setTxHash]=useState("");
 useEffect(()=>onAuthStateChanged(getClientAuth(),user=>{setSignedIn(Boolean(user));setAuthReady(true)}),[]);
 const order=async()=>{const user=getClientAuth().currentUser;if(!user){sessionStorage.setItem("saharasnow_return_to",window.location.pathname);window.location.href="/?signin=1";return}setBusy(true);setError("");try{const token=await user.getIdToken(true);const r=await fetch("/api/crypto/checkout",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({listingId,packageIndex})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to prepare USDT payment");setPayment(d);setTxHash("")}catch(e){setError(e instanceof Error?e.message:"Unable to prepare USDT payment")}finally{setBusy(false)}};
 const submit=async()=>{if(!payment)return;if(txHash.trim().length<16){setError("Paste the TRC20 transaction hash after sending USDT.");return}setBusy(true);setError("");try{const user=getClientAuth().currentUser;if(!user)throw new Error("Please sign in again.");const token=await user.getIdToken(true);const r=await fetch("/api/crypto/checkout",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({orderId:payment.orderId,txHash:txHash.trim()})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to submit payment");setPayment(null);alert("USDT payment submitted for verification. Your order will start after confirmation.");}catch(e){setError(e instanceof Error?e.message:"Unable to submit payment")}finally{setBusy(false)}};
 const qr=payment?`https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=${encodeURIComponent(payment.depositAddress)}`:"";
 return <div><button onClick={order} disabled={busy||!authReady}>{!authReady?"Checking sign-in…":busy?"Preparing USDT payment…":signedIn?`Pay with USDT — ${packageName||"this service"}`:`Sign in to choose ${packageName||"this service"}`}</button>{error&&!payment&&<p>{error}</p>}{payment&&<div style={{position:"fixed",inset:0,zIndex:100000,background:"rgba(15,23,42,.55)",display:"grid",placeItems:"center",padding:16}} onMouseDown={e=>{if(e.target===e.currentTarget)setPayment(null)}}><div style={{width:"min(520px,100%)",maxHeight:"90vh",overflow:"auto",background:"white",borderRadius:18,padding:24,position:"relative"}}><button type="button" onClick={()=>setPayment(null)} style={{position:"absolute",right:14,top:10,border:0,background:"transparent",fontSize:28,cursor:"pointer"}}>×</button><h2 style={{marginTop:0}}>Pay with USDT</h2><p>Send exactly <b>{(payment.amountCents/100).toFixed(2)} USDT</b> using <b>Tron (TRC20)</b>.</p><p><b>Zero deposit and checkout fees.</b></p><img src={qr} alt="USDT TRC20 payment QR code" width={220} height={220} style={{display:"block",margin:"16px auto",background:"white",padding:8,borderRadius:12}}/><label style={{display:"grid",gap:6,marginTop:12}}>Network<input readOnly value="Tron (TRC20)"/></label><label style={{display:"grid",gap:6,marginTop:12}}>USDT deposit address<input readOnly value={payment.depositAddress} onFocus={e=>e.currentTarget.select()}/></label><small>Send USDT only on TRC20 and verify the address before sending.</small><label style={{display:"grid",gap:6,marginTop:12}}>TRC20 transaction hash<input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="Paste transaction hash after sending"/></label>{error&&<p>{error}</p>}<button type="button" onClick={submit} disabled={busy} style={{marginTop:16,width:"100%"}}>{busy?"Submitting…":"I sent USDT — submit for verification"}</button></div></div>}</div>;
}
