"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {onAuthStateChanged} from "firebase/auth";
import {getClientAuth} from "@/lib/firebase-client";

type Payment={orderId:string;amountCents:number;depositAddress:string;network:string;qrCodeUrl:string;currency:string;paymentMethod:string};
type Method={id:"usdt-trc20"|"usdc-solana";currency:"USDT"|"USDC";network:string;shortNetwork:string;accent:string;description:string};
const METHODS:Method[]=[
 {id:"usdt-trc20",currency:"USDT",network:"Tron (TRC20)",shortNetwork:"TRC20",accent:"#26a17b",description:"Fast, stablecoin payment on Tron"},
 {id:"usdc-solana",currency:"USDC",network:"Solana",shortNetwork:"Solana",accent:"#2775ca",description:"USDC payment on Solana"},
];
const field:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #d7dde8",borderRadius:10,padding:"10px 12px",fontSize:14,background:"#fff",color:"#182230"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,fontWeight:800,color:"#526070"};
export default function OrderButton({listingId,packageIndex=0,packageName:_packageName}:{listingId:string;packageIndex?:number;packageName?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[authReady,setAuthReady]=useState(false),[signedIn,setSignedIn]=useState(false),[payment,setPayment]=useState<Payment|null>(null),[txHash,setTxHash]=useState(""),[copied,setCopied]=useState(false),[selectorOpen,setSelectorOpen]=useState(false),[selected,setSelected]=useState<Method>(METHODS[0]);
 useEffect(()=>onAuthStateChanged(getClientAuth(),user=>{setSignedIn(Boolean(user));setAuthReady(true)}),[]);
 useEffect(()=>{if(!payment)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old}},[payment]);
 const order=async(method:Method)=>{const user=getClientAuth().currentUser;if(!user){sessionStorage.setItem("saharasnow_return_to",window.location.pathname);window.location.href="/?signin=1";return}setBusy(true);setError("");try{const token=await user.getIdToken(true);const r=await fetch("/api/crypto/checkout",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({listingId,packageIndex,paymentMethod:method.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||`Unable to prepare ${method.currency} payment`);setPayment(d);setTxHash("");setCopied(false);setSelectorOpen(false)}catch(e){setError(e instanceof Error?e.message:`Unable to prepare ${method.currency} payment`)}finally{setBusy(false)}};
 const submit=async()=>{if(!payment)return;if(txHash.trim().length<16){setError(`Paste the ${payment.network} transaction hash after sending ${payment.currency}.`);return}setBusy(true);setError("");try{const user=getClientAuth().currentUser;if(!user)throw new Error("Please sign in again.");const token=await user.getIdToken(true);const r=await fetch("/api/crypto/checkout",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({orderId:payment.orderId,txHash:txHash.trim()})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to submit payment");setPayment(null);alert(`${payment.currency} payment submitted for verification. Your order will start after confirmation.`)}catch(e){setError(e instanceof Error?e.message:"Unable to submit payment")}finally{setBusy(false)}};
 const copyAddress=async()=>{if(!payment)return;try{await navigator.clipboard.writeText(payment.depositAddress);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setError("Could not copy the deposit address.")}};
 const amount=(payment?.amountCents||0)/100;
 const copyButtonStyle:React.CSSProperties={padding:"11px 15px",borderRadius:10,border:"1px solid #94a3b8",background:"#ffffff",fontWeight:800,cursor:"pointer",fontSize:13,color:"#111827",WebkitTextFillColor:"#111827",opacity:1,visibility:"visible",display:"inline-flex",alignItems:"center",justifyContent:"center",minHeight:42,boxShadow:"0 1px 2px rgba(0,0,0,.06)"};
 return <div style={{display:"grid",gap:10}}>
  <button type="button" onClick={()=>setSelectorOpen(v=>!v)} disabled={busy||!authReady} aria-haspopup="dialog" aria-expanded={selectorOpen} style={{width:"100%",padding:"16px 18px",border:0,borderRadius:16,background:"linear-gradient(135deg,#172235,#253b5b)",color:"white",fontWeight:900,fontSize:16,cursor:"pointer",boxShadow:"0 12px 30px rgba(23,34,53,.18)",display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><span style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:32,height:32,borderRadius:10,display:"grid",placeItems:"center",background:"rgba(255,255,255,.12)",fontSize:18}}>₿</span><span>{!authReady?"Checking sign-in…":busy?"Preparing payment…":signedIn?"Choose payment method":"Sign in to order"}</span></span><span style={{fontSize:18,opacity:.8}}>{selectorOpen?"⌃":"⌄"}</span></button>
  {error&&!payment&&<p style={{margin:0,color:"#b42318",fontWeight:700}}>{error}</p>}
  {selectorOpen&&signedIn&&<div role="dialog" aria-label="Choose payment method" style={{border:"1px solid #e3e8ef",borderRadius:18,padding:12,background:"linear-gradient(180deg,#fff,#f7f9fc)",boxShadow:"0 18px 45px rgba(16,24,40,.16)",display:"grid",gap:8}}><div style={{fontSize:11,fontWeight:900,letterSpacing:".08em",textTransform:"uppercase",color:"#738094",padding:"2px 4px 3px"}}>Pay securely with crypto</div>{METHODS.map(method=><button key={method.id} type="button" onClick={()=>{setSelected(method);void order(method)}} disabled={busy} style={{textAlign:"left",padding:11,border:`1px solid ${selected.id===method.id?method.accent:"#e2e7ee"}`,borderRadius:14,background:"white",cursor:"pointer",display:"grid",gridTemplateColumns:"38px 1fr auto",alignItems:"center",gap:10,boxShadow:selected.id===method.id?`0 8px 24px ${method.accent}22`:"none"}}><span style={{width:38,height:38,borderRadius:11,display:"grid",placeItems:"center",background:`${method.accent}14`,color:method.accent,fontWeight:950,fontSize:11}}>{method.currency}</span><span><strong style={{display:"block",fontSize:14,color:"#172235"}}>{method.currency}</strong><small style={{display:"block",marginTop:2,color:"#687588",fontSize:12}}>{method.description}</small></span><span style={{fontSize:11,fontWeight:900,color:method.accent}}>{method.shortNetwork} →</span></button>)}</div>}
  {payment&&createPortal(<div role="presentation" style={{position:"fixed",inset:0,zIndex:100000,background:"rgba(10,18,32,.72)",backdropFilter:"blur(7px)",display:"grid",placeItems:"center",padding:20,boxSizing:"border-box"}}><div role="dialog" aria-modal="true" aria-label={`${payment.currency} payment`} style={{position:"relative",width:"min(980px,100%)",maxHeight:"95vh",overflowY:"auto",overflowX:"hidden",boxSizing:"border-box",background:"linear-gradient(135deg,#ffffff,#f7f9fc)",borderRadius:20,boxShadow:"0 24px 70px rgba(16,24,40,.28)"}}><button type="button" aria-label="Close payment and return to site" onClick={()=>setPayment(null)} style={{position:"fixed",right:"clamp(12px,3vw,24px)",top:"clamp(12px,3vw,24px)",width:42,height:42,borderRadius:"50%",border:"2px solid rgba(255,255,255,.9)",background:"#172235",fontSize:22,lineHeight:1,cursor:"pointer",zIndex:100002,color:"#fff",display:"grid",placeItems:"center",boxShadow:"0 6px 22px rgba(0,0,0,.4)"}}>×</button>
   <main style={{boxSizing:"border-box",padding:"clamp(20px,3vw,30px)",display:"grid",gap:"clamp(16px,2.5vw,22px)"}}>
    <header style={{paddingRight:"clamp(40px,6vw,56px)"}}><div style={{display:"inline-flex",alignItems:"center",gap:7,padding:"6px 10px",borderRadius:999,background:payment.currency==="USDC"?"#eef5ff":"#ecf8f2",color:payment.currency==="USDC"?"#1e5fae":"#18794e",fontSize:11,fontWeight:900}}>🔒 Secure {payment.currency} checkout</div><h2 style={{margin:"9px 0 5px",fontSize:"clamp(24px,3.6vw,34px)",lineHeight:1.05,letterSpacing:"-.03em",color:"#152033",overflowWrap:"break-word"}}>Pay with {payment.currency}</h2><p style={{margin:0,fontSize:14,color:"#667386",lineHeight:1.45}}>Send the exact amount using <b style={{color:"#152033"}}>{payment.network}</b>. Your order will begin after payment verification.</p></header>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:"clamp(16px,2.5vw,24px)",alignItems:"start"}}>
     <section style={{minWidth:0,display:"grid",placeItems:"center",padding:"clamp(16px,2.4vw,24px)",borderRadius:22,background:payment.currency==="USDC"?"linear-gradient(145deg,#eef5ff,#f8fbff)":"linear-gradient(145deg,#eef8f4,#f8fbfa)",border:`1px solid ${payment.currency==="USDC"?"#d8e6f8":"#dcebe4"}`}}><div style={{textAlign:"center",width:"100%"}}><div style={{fontSize:11,fontWeight:900,letterSpacing:".08em",color:"#6d7b8b",textTransform:"uppercase"}}>Scan to pay</div><img src={payment.qrCodeUrl} alt={`${payment.currency} payment QR code`} width={220} height={220} style={{display:"block",width:"min(220px,55vw)",height:"auto",margin:"12px auto 14px",background:"white",padding:10,borderRadius:18,boxShadow:"0 10px 25px rgba(29,74,54,.10)"}}/><div style={{display:"inline-flex",gap:7,alignItems:"center",padding:"7px 11px",background:"white",borderRadius:999,border:"1px solid #dcebe4",fontWeight:800,fontSize:12,color:payment.currency==="USDC"?"#1e5fae":"#18794e",maxWidth:"100%",boxSizing:"border-box"}}>{payment.currency} • {payment.currency==="USDC"?"Solana":"TRC20"}</div></div></section>
     <section style={{display:"grid",gap:11,minWidth:0}}><div style={{padding:"17px 20px",borderRadius:18,background:"#172235",color:"white"}}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:".08em",opacity:.65}}>Amount to send</div><div style={{fontSize:"clamp(30px,5vw,40px)",fontWeight:900,letterSpacing:"-.045em",marginTop:2,overflowWrap:"anywhere",lineHeight:1}}>{amount.toFixed(2)} <span style={{fontSize:".46em",opacity:.75}}>{payment.currency}</span></div><div style={{marginTop:7,opacity:.72,fontSize:12}}>Includes 1% buyer fee • Send the exact amount</div></div><label style={label}>Network<input readOnly value={payment.network} style={field}/></label><label style={label}>{payment.currency} deposit address<input readOnly value={payment.depositAddress} onFocus={e=>e.currentTarget.select()} style={{...field,fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace",fontSize:12}}/></label><button type="button" onClick={copyAddress} aria-label={copied?"Address copied":"Copy deposit address"} style={copyButtonStyle}><span style={{color:"#111827",WebkitTextFillColor:"#111827",opacity:1,visibility:"visible",fontWeight:800}}>{copied?"✓ Address copied":"Copy deposit address"}</span></button><div style={{padding:"10px 12px",borderRadius:12,background:"#fff7e8",color:"#7a5712",fontSize:12,lineHeight:1.4}}>⚠️ Send <b>{payment.currency} only on the {payment.network} network</b>. Verify the address before sending.</div></section>
    </div>
    <section style={{borderTop:"1px solid #e4e8ef",paddingTop:18,display:"grid",gap:9}}><div style={{fontWeight:900,fontSize:16,color:"#172235"}}>After you send the payment</div><label style={label}>{payment.network} transaction hash<input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="Paste your transaction hash here" style={field}/></label>{error&&<p style={{margin:0,color:"#b42318",fontWeight:700,fontSize:13}}>{error}</p>}<button type="button" onClick={submit} disabled={busy} style={{marginTop:2,width:"100%",padding:"13px 18px",border:0,borderRadius:12,background:payment.currency==="USDC"?"#2775ca":"#18794e",color:"white",fontWeight:900,fontSize:14,cursor:"pointer"}}>{busy?"Submitting…":`I sent ${payment.currency} — submit for verification`}</button></section>
   </main>
  </div></div>,document.body)}
 </div>;
}
