"use client";
import {useEffect,useState} from "react";
import {getClientAuth} from "@/lib/firebase-client";

type Review={id:string;rating:number;text:string;verifiedPurchase?:boolean;createdAt?:{_seconds?:number};buyerName?:string};
export default function ReviewSection({sellerId}:{sellerId:string}){
  const [reviews,setReviews]=useState<Review[]>([]);const [summary,setSummary]=useState({count:0,average:0});const [eligibleOrderIds,setEligibleOrderIds]=useState<string[]>([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;(async()=>{try{const auth=getClientAuth();const user=auth.currentUser;const headers:Record<string,string>={};if(user)headers.authorization=`Bearer ${await user.getIdToken()}`;const r=await fetch(`/api/reviews?sellerId=${encodeURIComponent(sellerId)}`,{headers,cache:"no-store"});const d=await r.json();if(!cancelled){setReviews(Array.isArray(d.reviews)?d.reviews:[]);setSummary(d.summary||{count:0,average:0});setEligibleOrderIds(Array.isArray(d.eligibleOrderIds)?d.eligibleOrderIds:[]);}}catch{}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[sellerId]);
  const stars=(n:number)=>"★★★★★".slice(0,Math.max(0,Math.min(5,n)))+"☆☆☆☆☆".slice(0,5-Math.max(0,Math.min(5,n)));
  return <section style={{marginTop:32,paddingTop:28,borderTop:"1px solid #e7e2da"}}><div style={{display:"flex",alignItems:"end",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><small style={{letterSpacing:".12em",fontWeight:700,color:"#777"}}>SELLER REVIEWS</small><h2 style={{margin:"6px 0 4px"}}>Reviews & rating</h2></div><div style={{textAlign:"right"}}><strong style={{fontSize:28}}>{summary.average.toFixed(1)}</strong><div style={{letterSpacing:2}}>{stars(Math.round(summary.average))}</div><small>{summary.count} {summary.count===1?"review":"reviews"}</small></div></div>{eligibleOrderIds.length>0&&<div style={{marginTop:18,padding:16,borderRadius:14,background:"#f7f5ff",border:"1px solid #e5e0ff"}}><b>Share your experience</b><p style={{margin:"6px 0 12px",color:"#666"}}>You have a completed order with this seller. Your verified rating helps other buyers.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{eligibleOrderIds.map(id=><a key={id} href={`/review/${encodeURIComponent(id)}`} style={{display:"inline-flex",alignItems:"center",justifyContent:"center",padding:"10px 15px",borderRadius:10,background:"#17134f",color:"#fff",fontWeight:700,textDecoration:"none"}}>★ Leave a review</a>)}</div></div>}{loading?<p>Loading reviews…</p>:reviews.length===0?<p style={{color:"#777"}}>No reviews yet. Completed buyers can leave the first verified review.</p>:<div style={{display:"grid",gap:14,marginTop:18}}>{reviews.map(r=><article key={r.id} style={{padding:"16px 18px",border:"1px solid #e7e2da",borderRadius:14}}><div><b style={{letterSpacing:1}}>{stars(r.rating)}</b>{r.verifiedPurchase&&<span style={{marginLeft:10,fontSize:12,fontWeight:700}}>✓ Verified purchase</span>}</div><p style={{margin:"10px 0 0",lineHeight:1.55}}>{r.text}</p></article>)}</div>}</section>;
}
