"use client";
import {useEffect,useState} from "react";

type Review={id:string;rating:number;text:string;verifiedPurchase?:boolean;createdAt?:{_seconds?:number};buyerName?:string};
export default function ReviewSection({sellerId}:{sellerId:string}){
  const [reviews,setReviews]=useState<Review[]>([]);const [summary,setSummary]=useState({count:0,average:0});const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;fetch(`/api/reviews?sellerId=${encodeURIComponent(sellerId)}`).then(r=>r.json()).then(d=>{if(!cancelled){setReviews(Array.isArray(d.reviews)?d.reviews:[]);setSummary(d.summary||{count:0,average:0});}}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[sellerId]);
  const stars=(n:number)=>"★★★★★".slice(0,Math.max(0,Math.min(5,n)))+"☆☆☆☆☆".slice(0,5-Math.max(0,Math.min(5,n)));
  return <section style={{marginTop:32,paddingTop:28,borderTop:"1px solid #e7e2da"}}><div style={{display:"flex",alignItems:"end",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><small style={{letterSpacing:".12em",fontWeight:700,color:"#777"}}>SELLER REVIEWS</small><h2 style={{margin:"6px 0 4px"}}>Reviews & rating</h2></div><div style={{textAlign:"right"}}><strong style={{fontSize:28}}>{summary.average.toFixed(1)}</strong><div style={{letterSpacing:2}}>{stars(Math.round(summary.average))}</div><small>{summary.count} {summary.count===1?"review":"reviews"}</small></div></div>{loading?<p>Loading reviews…</p>:reviews.length===0?<p style={{color:"#777"}}>No reviews yet. Completed buyers will be able to leave the first verified review.</p>:<div style={{display:"grid",gap:14,marginTop:18}}>{reviews.map(r=><article key={r.id} style={{padding:"16px 18px",border:"1px solid #e7e2da",borderRadius:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><b style={{letterSpacing:1}}>{stars(r.rating)}</b>{r.verifiedPurchase&&<span style={{marginLeft:10,fontSize:12,fontWeight:700}}>✓ Verified purchase</span>}</div></div><p style={{margin:"10px 0 0",lineHeight:1.55}}>{r.text}</p></article>)}</div>}</section>;
}
