import { NextRequest, NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { db } from "@/lib/firebase-admin";
import { userFromRequest } from "@/lib/server";

const ADMIN_EMAIL=(process.env.SUPER_ADMIN_EMAIL||"yiorgosantoni@gmail.com").toLowerCase();
async function requireAdmin(req:NextRequest){const user=await userFromRequest(req);if((user.email||"").toLowerCase()!==ADMIN_EMAIL)throw new Error("ADMIN_FORBIDDEN");return user;}
const schema=z.object({reviewId:z.string().min(1),action:z.enum(["delete","reset"]),note:z.string().trim().max(500).optional()});
async function recalculateSeller(sellerId:string){const snap=await db.collection("reviews").where("sellerId","==",sellerId).get();let count=0,sum=0;snap.forEach(doc=>{const rating=Number(doc.data().rating);if(Number.isFinite(rating)&&rating>=1&&rating<=5){count++;sum+=rating;}});await db.collection("users").doc(sellerId).set({reviewCount:count,reviewRatingSum:sum,averageRating:count?sum/count:0,updatedAt:FieldValue.serverTimestamp()},{merge:true});return {count,sum};}
export async function GET(req:NextRequest){try{await requireAdmin(req);const snap=await db.collection("reviews").get();const reviews=snap.docs.map(d=>({id:d.id,...d.data()}));return NextResponse.json({reviews});}catch(e){return NextResponse.json({error:"Only the SaharaSnow administrator can access review moderation."},{status:403});}}
export async function PATCH(req:NextRequest){try{const admin=await requireAdmin(req);const body=schema.parse(await req.json());const ref=db.collection("reviews").doc(body.reviewId);const snap=await ref.get();if(!snap.exists)return NextResponse.json({error:"Review not found"},{status:404});const review=snap.data()||{};const sellerId=String(review.sellerId||"");const orderId=String(review.orderId||"");if(!sellerId||!orderId)return NextResponse.json({error:"Review is missing seller or order information"},{status:400});await ref.delete();const totals=await recalculateSeller(sellerId);await db.collection("auditLogs").add({adminUid:admin.uid,adminEmail:admin.email||ADMIN_EMAIL,resource:"review",resourceId:body.reviewId,action:body.action,note:body.note||"",sellerId,orderId,createdAt:FieldValue.serverTimestamp()});return NextResponse.json({ok:true,deleted:true,reviewReset:body.action==="reset",rating:totals});}catch(e){const message=e instanceof Error?e.message:"Unable to moderate review";return NextResponse.json({error:message==="ADMIN_FORBIDDEN"?"Only the SaharaSnow administrator can moderate reviews.":"Unable to moderate review."},{status:message==="ADMIN_FORBIDDEN"?403:400});}}
