"use client";
import {useEffect,useState} from "react";
import {getClientAuth} from "@/lib/firebase-client";

type Conversation={id:string;otherUser:{id:string;name:string}};
const token=async()=>{const u=getClientAuth().currentUser;if(!u)throw new Error("Please sign in first.");return u.getIdToken();};
export default function CustomOrderInvoice(){
 const [open,setOpen]=useState(false),[conversations,setConversations]=useState<Conversation[]>([]),[sellerId,setSellerId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[amount,setAmount]=useState("5"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const verify=async()=>{const sessionId=new URLSearchParams(location.search).get("customInvoiceSuccess");if(!sessionId)return;try{const t=await token();const r=await fetch("/api/custom-invoices",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({sessionId})});if(!r.ok)throw new Error((await r.json()).error||"Could not confirm payment");history.replaceState({},"",location.pathname+location.search.replace(/[?&]customInvoiceSuccess=[^&]+/,"").replace(/^&/,"?"));alert("Payment confirmed. Your custom order is now in progress.");}catch(e){alert(e instanceof Error?e.message:"Payment confirmation failed");}};verify();},[]);
 const load=async()=>{try{const t=await token();const r=await fetch("/api/messages",{headers:{authorization:`Bearer ${t}`}});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load inbox contacts");setConversations(data.conversations||[]);setSellerId(data.conversations?.[0]?.otherUser?.id||"");setOpen(true);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not open invoice form");setOpen(true);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const cents=Math.round(Number(amount)*100);if(!sellerId){setError("Choose a seller.");return}if(!Number.isFinite(cents)||cents<500){setError("Custom orders must be at least $5 USD.");return}setBusy(true);setError("");try{const t=await token();const r=await fetch("/api/custom-invoices",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({sellerId,title,description,amountCents:cents})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not create invoice");location.href=data.checkoutUrl;}catch(e){setError(e instanceof Error?e.message:"Could not create invoice");setBusy(false)}};
 return <><button className="customInvoiceButton" onClick={load} aria-label="Create custom order invoice">💳 Custom order</button>{open&&<div className="customInvoiceOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="customInvoiceModal" onSubmit={submit}><button type="button" className="customInvoiceClose" onClick={()=>setOpen(false)}>×</button><div className="customInvoiceIcon">🧾</div><h2>Create a custom order</h2><p>Send a protected custom order payment through Stripe. Minimum <b>$5 USD</b>.</p>{error&&<div className="customInvoiceError">{error}</div>}<label>Seller<select value={sellerId} onChange={e=>setSellerId(e.target.value)} required><option value="">Choose a seller</option>{conversations.map(c=><option key={c.id} value={c.otherUser.id}>{c.otherUser.name}</option>)}</select></label><label>Order title<input value={title} onChange={e=>setTitle(e.target.value)} minLength={3} maxLength={160} required placeholder="What do you need?"/></label><label>Details<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} placeholder="Describe the custom work"/></label><label>Amount (USD)<input type="number" min="5" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button className="customInvoicePay" disabled={busy}>{busy?"Opening secure payment…":"Continue to secure payment →"}</button></form></div>}</>;
}
