"use client";
import {useEffect,useRef,useState} from "react";
import {getClientAuth,observeAuth} from "@/lib/firebase-client";

type Favorite={id:string;title:string;category:string;subcategory:string;sellerName:string;photoUrls:string[];priceCents:number};
export default function FavouriteManager(){
 const[open,setOpen]=useState(false);const[items,setItems]=useState<Favorite[]>([]);const[loading,setLoading]=useState(false);const[notice,setNotice]=useState("");const[signedIn,setSignedIn]=useState(false);const itemsRef=useRef<Favorite[]>([]);
 useEffect(()=>{itemsRef.current=items},[items]);
 const token=async()=>{const user=getClientAuth().currentUser;if(!user)throw new Error("Please sign in to save services.");return user.getIdToken();};
 const paintHearts=()=>{const saved=new Set(itemsRef.current.map(x=>x.id));document.querySelectorAll<HTMLButtonElement>("article[id^='service-'] .favouriteButton").forEach(button=>{const article=button.closest<HTMLElement>("article[id^='service-']");const id=article?.id.replace(/^service-/,"");if(!id)return;button.textContent=saved.has(id)?"♥":"♡";button.setAttribute("aria-pressed",String(saved.has(id)));button.setAttribute("aria-label",saved.has(id)?"Remove from favourites":"Save to favourites")})};
 const load=async()=>{try{setLoading(true);const t=await token();const r=await fetch("/api/favorites",{headers:{authorization:`Bearer ${t}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load favourites");const next=Array.isArray(d.favorites)?d.favorites:[];setItems(next);itemsRef.current=next;requestAnimationFrame(paintHearts)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load favourites")}finally{setLoading(false)}};
 useEffect(()=>observeAuth(ok=>{setSignedIn(ok);if(ok)void load();else{setItems([]);itemsRef.current=[];requestAnimationFrame(paintHearts)}}),[]);
 useEffect(()=>{const onClick=async(event:MouseEvent)=>{const target=event.target instanceof Element?event.target:null;const button=target?.closest<HTMLButtonElement>("article[id^='service-'] .favouriteButton");if(!button)return;event.preventDefault();event.stopImmediatePropagation();const article=button.closest<HTMLElement>("article[id^='service-']");const listingId=article?.id.replace(/^service-/,"");if(!listingId)return;const user=getClientAuth().currentUser;if(!user){window.location.assign("/?signin=1");return}button.disabled=true;try{const saved=itemsRef.current.some(x=>x.id===listingId);const t=await user.getIdToken(true);const r=await fetch("/api/favorites",{method:saved?"DELETE":"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({listingId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update favourite");if(d.saved){const existing=itemsRef.current.find(x=>x.id===listingId);const fallback:Favorite={id:listingId,title:"Saved service",category:"Service",subcategory:"",sellerName:"",photoUrls:[],priceCents:0};const next=existing?[...itemsRef.current]:[...itemsRef.current,fallback];itemsRef.current=next;setItems(next);button.textContent="♥";button.setAttribute("aria-pressed","true");button.setAttribute("aria-label","Remove from favourites")}else{const next=itemsRef.current.filter(x=>x.id!==listingId);itemsRef.current=next;setItems(next);button.textContent="♡";button.setAttribute("aria-pressed","false");button.setAttribute("aria-label","Save to favourites")}}catch(error){setNotice(error instanceof Error?error.message:"Unable to update favourite")}finally{button.disabled=false}};
 document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true)},[]);
 useEffect(()=>{const root=document.querySelector(".accountActions");if(!root)return;const existing=root.querySelector("[data-favourites-trigger]");if(existing)return;const button=document.createElement("button");button.type="button";button.setAttribute("data-favourites-trigger","true");button.setAttribute("aria-label","Favourites");button.textContent="♡";button.onclick=()=>{if(!signedIn){setNotice("Please sign in to save services.");return}setOpen(true);void load()};root.insertBefore(button,root.firstChild);return()=>button.remove()},[signedIn]);
 if(!open)return notice?<div className="favouriteToast" onAnimationEnd={()=>setNotice("")}>{notice}</div>:null;
 return <div className="backdrop" onMouseDown={()=>setOpen(false)}><div className="accountModal favouriteModal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button><div className="accountTop"><img src="/logo.png" alt="Saharasnow"/><div><small>BUYER</small><h2>FAVOURITES</h2></div></div><div className="accountTabs"><button className="active">Saved services</button></div>{notice&&<p className="listingNotice">{notice}</p>}{loading?<div className="noOrders"><b>Loading your saved services…</b></div>:items.length===0?<div className="noOrders"><b>No favourite services yet</b><p>Click the ♡ on any service to save it here.</p></div>:<div className="myServicesGrid">{items.map(item=><article key={item.id} onClick={()=>location.assign(`/service/${encodeURIComponent((item.subcategory||item.category||"service").toLowerCase().replace(/[^a-z0-9]+/g,"-"))}/${item.id}`)}><img src={item.photoUrls?.[0]||"/logo.png"} alt=""/><div><small>{item.category} · {item.subcategory}</small><h4>{item.title}</h4><strong>From €{(item.priceCents/100).toFixed(2)}</strong><button className="deleteServiceButton" onClick={e=>{e.stopPropagation();void (async()=>{try{const t=await token();const r=await fetch("/api/favorites",{method:"DELETE",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({listingId:item.id})});if(!r.ok)return;const next=itemsRef.current.filter(x=>x.id!==item.id);itemsRef.current=next;setItems(next);requestAnimationFrame(paintHearts)}catch(error){setNotice(error instanceof Error?error.message:"Unable to remove favourite")}})()}}>Remove</button></div></article>)}</div>}</div></div>;
}
