"use client";
import {useEffect,useRef,useState} from "react";
import {getClientAuth,observeAuth} from "@/lib/firebase-client";

type Favorite={id:string;title:string;category:string;subcategory:string;sellerName:string;photoUrls:string[];priceCents:number};

export default function FavouriteManager(){
 const[open,setOpen]=useState(false);const[items,setItems]=useState<Favorite[]>([]);const[loading,setLoading]=useState(false);const[notice,setNotice]=useState("");const[signedIn,setSignedIn]=useState(false);const syncing=useRef(false);
 const token=async()=>{const user=getClientAuth().currentUser;if(!user)throw new Error("Please sign in to save services.");return user.getIdToken();};
 const load=async()=>{try{setLoading(true);const t=await token();const r=await fetch("/api/favorites",{headers:{authorization:`Bearer ${t}`},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load favourites");setItems(Array.isArray(d.favorites)?d.favorites:[])}catch(e){setNotice(e instanceof Error?e.message:"Unable to load favourites")}finally{setLoading(false)}};
 const toggle=async(button:HTMLElement,id:string)=>{try{const t=await token();const saved=button.getAttribute("aria-pressed")==="true";const r=await fetch("/api/favorites",{method:saved?"DELETE":"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({listingId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update favourite");button.setAttribute("aria-pressed",String(!saved));button.textContent=!saved?"♥":"♡";button.setAttribute("aria-label",!saved?"Remove from favourites":"Save service");if(!saved){const favourite=d.favorite;if(favourite)setItems(v=>v.some(x=>x.id===id)?v:[...v,favourite]);}else setItems(v=>v.filter(x=>x.id!==id));if(open&&!saved)await load()}catch(e){setNotice(e instanceof Error?e.message:"Unable to update favourite")}};
 useEffect(()=>observeAuth(ok=>{setSignedIn(ok);if(ok)void load();else setItems([])}),[]);
 useEffect(()=>{
   const sync=()=>{if(syncing.current)return;syncing.current=true;try{document.querySelectorAll<HTMLElement>(".favouriteButton").forEach(button=>{const article=button.closest("article[id^='service-']");const id=article?.id.replace(/^service-/ ,"");if(!id)return;const saved=items.some(item=>item.id===id);const text=saved?"♥":"♡";const pressed=String(saved);const label=saved?"Remove from favourites":"Save service";if(button.textContent!==text)button.textContent=text;if(button.getAttribute("aria-pressed")!==pressed)button.setAttribute("aria-pressed",pressed);if(button.getAttribute("aria-label")!==label)button.setAttribute("aria-label",label);button.onclick=(event)=>{event.preventDefault();event.stopPropagation();void toggle(button,id)}})}finally{syncing.current=false}};
   sync();let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;sync()})});observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();
 },[items,open]);
 useEffect(()=>{const root=document.querySelector(".accountActions");if(!root)return;const existing=root.querySelector("[data-favourites-trigger]");if(existing)return;const button=document.createElement("button");button.type="button";button.setAttribute("data-favourites-trigger","true");button.setAttribute("aria-label","Favourites");button.textContent="♡";button.onclick=()=>{if(!signedIn){setNotice("Please sign in to save services.");return}setOpen(true);void load()};root.insertBefore(button,root.firstChild);return()=>{button.remove()};},[signedIn]);
 if(!open)return notice?<div className="favouriteToast" onAnimationEnd={()=>setNotice("")}>{notice}</div>:null;
 return <div className="backdrop" onMouseDown={()=>setOpen(false)}><div className="accountModal favouriteModal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button><div className="accountTop"><img src="/logo.png" alt="Saharasnow"/><div><small>BUYER</small><h2>FAVOURITES</h2></div></div><div className="accountTabs"><button className="active">Saved services</button></div>{notice&&<p className="listingNotice">{notice}</p>}{loading?<div className="noOrders"><b>Loading your saved services…</b></div>:items.length===0?<div className="noOrders"><b>No favourite services yet</b><p>Click the ♡ on any service to save it here.</p></div>:<div className="myServicesGrid">{items.map(item=><article key={item.id} onClick={()=>location.assign(`/service/${encodeURIComponent((item.subcategory||item.category||"service").toLowerCase().replace(/[^a-z0-9]+/g,"-"))}/${item.id}`)}><img src={item.photoUrls?.[0]||"/logo.png"} alt=""/><div><small>{item.category} · {item.subcategory}</small><h4>{item.title}</h4><strong>From €{(item.priceCents/100).toFixed(2)}</strong><button className="deleteServiceButton" onClick={e=>{e.stopPropagation();void (async()=>{try{const t=await token();const r=await fetch("/api/favorites",{method:"DELETE",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({listingId:item.id})});if(!r.ok)return;setItems(v=>v.filter(x=>x.id!==item.id));document.querySelectorAll<HTMLElement>(".favouriteButton").forEach(b=>{const a=b.closest("article[id^='service-']");if(a?.id===`service-${item.id}`){b.textContent="♡";b.setAttribute("aria-pressed","false");b.setAttribute("aria-label","Save service")}})}catch(e){setNotice(e instanceof Error?e.message:"Unable to remove favourite")}})()}}>Remove</button></div></article>)}</div>}</div></div>;
}
