"use client";
import { FormEvent,useMemo,useState } from "react";
import { getDownloadURL,ref,uploadBytesResumable } from "firebase/storage";
import { getClientAuth,getClientStorage } from "@/lib/firebase-client";
import { renderRichText } from "@/lib/richText";
import RichTextToolbar from "./RichTextToolbar";

const TITLE_PREFIX="I will ";

const subcategories:Record<string,string[]>={
  "Graphics & Design": [
    "Logo Design",
    "Brand Style Guides",
    "Business Cards & Stationery",
    "Fonts & Typography",
    "Art Direction",
    "Illustration",
    "AI Artists",
    "AI Avatar Design",
    "Portraits & Caricatures",
    "Comic Illustration",
    "Cartoon Illustration",
    "Storyboards",
    "Album Cover Design",
    "Pattern Design",
    "Tattoo Design",
    "Design Consultation",
    "Website Design",
    "App Design",
    "UX Design",
    "Landing Page Design",
    "Icon Design",
    "E-Commerce Website Design",
    "Industrial & Product Design",
    "Character Modeling",
    "Game Art",
    "Graphics for Streamers",
    "Brochure Design",
    "Flyer Design",
    "Packaging & Label Design",
    "Poster Design",
    "Catalog Design",
    "Menu Design",
    "Book Design",
    "Book Covers",
    "Book Layout Design & Typesetting",
    "Children's Book Illustration",
    "Comic Book Illustration",
    "Image Editing",
    "Presentation Design",
    "Resume Design",
    "Virtual Backgrounds",
    "Infographic Design",
    "Vector Tracing",
    "Social Media Design",
    "Email Design",
    "Web Banners",
    "Signage Design",
    "Architecture & Interior Design",
    "Landscape Design",
    "Building Engineering",
    "Lighting Design",
    "T-Shirts & Merchandise",
    "Fashion Design",
    "Jewelry Design",
    "3D Architecture",
    "3D Industrial Design",
    "3D Fashion & Garment",
    "3D Printing Characters",
    "3D Landscape",
    "3D Game Art",
    "3D Jewelry Design"
  ],
  "Programming & Tech": [
    "Business Websites",
    "E-Commerce Development",
    "Custom Websites",
    "Landing Pages",
    "Dropshipping Websites",
    "WordPress",
    "Shopify",
    "Wix",
    "Webflow",
    "Bubble",
    "Website Customization",
    "Bug Fixes",
    "Backup & Migration",
    "Speed Optimization",
    "AI Websites & Software",
    "AI Mobile Apps",
    "AI Integrations",
    "AI Agents",
    "AI Technology Consulting",
    "Development & MVP",
    "Troubleshooting & Improvements",
    "Deployments & DevOps",
    "Cross-platform Development",
    "Android App Development",
    "iOS App Development",
    "Mobile App Maintenance",
    "AI Chatbot",
    "Rules Based Chatbot",
    "Unreal Engine",
    "Unity Developers",
    "Roblox",
    "Fivem",
    "Cloud Computing",
    "DevOps Engineering",
    "Cybersecurity",
    "Full Stack Web Apps",
    "Automations & Agents",
    "APIs & Integrations",
    "Databases",
    "QA & Review",
    "User Testing",
    "Decentralized Apps (dApps)",
    "Cryptocurrencies & Tokens",
    "Electronics Engineering",
    "Support & IT",
    "Machine Learning",
    "Data Tagging & Annotation",
    "Convert Files"
  ],
  "Digital Marketing": [
    "Search Engine Optimization (SEO)",
    "Generative Engine Optimization (GEO)",
    "Search Engine Marketing (SEM)",
    "Local SEO",
    "E-Commerce SEO",
    "Video SEO",
    "Social Media Marketing",
    "Paid Social Media",
    "Social Commerce",
    "Influencer Marketing",
    "Online Communities",
    "TikTok Shop",
    "Facebook Ads Campaign",
    "Instagram Marketing",
    "YouTube Promotion",
    "Google SEM",
    "Shopify Marketing",
    "Video Marketing",
    "E-Commerce Marketing",
    "Email Marketing",
    "Email Automations",
    "Marketing Automation",
    "Guest Posting",
    "Affiliate Marketing",
    "Display Advertising",
    "Public Relations",
    "Crowdfunding",
    "Text Message Marketing",
    "AI Marketing Prompt Strategy",
    "Brand Personality Design",
    "Email Marketing Personalization",
    "AI-Powered Campaign Management",
    "AI-Powered Ad Bidding & Automation",
    "Marketing Strategy",
    "Marketing Consultation",
    "Marketing Concepts & Ideation",
    "Conversion Rate Optimization (CRO)",
    "Conscious Branding & Marketing",
    "Web Analytics",
    "Music Promotion",
    "Podcast Marketing",
    "Mobile App Marketing",
    "Book & eBook Marketing"
  ],
  "Video & Animation": [
    "Video Editing",
    "Visual Effects",
    "Intro & Outro Videos",
    "Video Repurposing",
    "Video Templates Editing",
    "Subtitles & Captions",
    "Video Ads & Commercials",
    "Social Media Videos",
    "Music Videos",
    "Slideshow Videos",
    "UGC Videos",
    "TikTok UGC Videos",
    "Instagram UGC Videos",
    "Spokesperson Videos",
    "Logo Animation",
    "Lottie & Web Animation",
    "Text Animation",
    "Video Art Creation",
    "Character Animation",
    "Animated GIFs",
    "Animation for Kids",
    "Animation for Streamers",
    "Rigging",
    "NFT Animation",
    "Videographers",
    "Drone Videography",
    "Filmed Video Production",
    "Animated Explainers",
    "Live Action Explainers",
    "Screencasting Videos",
    "eLearning Video Production",
    "Crowdfunding Videos",
    "3D Product Animation",
    "E-Commerce Product Videos",
    "Corporate Videos",
    "App & Website Previews",
    "AI UGC",
    "AI Videography",
    "AI Music Videos",
    "AI Video Avatars",
    "Virtual & Streaming Avatars",
    "Article to Video",
    "Game Trailers",
    "Game Recordings & Guides",
    "Meditation Videos",
    "Real Estate Promos",
    "Book Trailers",
    "Video Consultation",
    "Other"
  ],
  "Writing & Translation": [
    "Articles & Blog Posts",
    "Content Strategy",
    "Website Content",
    "Scriptwriting",
    "Creative Writing",
    "Podcast Writing",
    "Speechwriting",
    "Research & Summaries",
    "Proofreading & Editing",
    "Academic Support",
    "AI Content Editing",
    "Writing Advice",
    "Book & eBook Writing",
    "Book Editing",
    "Developmental Editing",
    "Line Editing",
    "Beta Reading",
    "Books & literature translation",
    "Resume Writing",
    "Cover Letters",
    "LinkedIn Profiles",
    "Job Descriptions",
    "Brand Voice & Tone",
    "Business Names & Slogans",
    "Case Studies",
    "Product Descriptions",
    "Ad Copy",
    "Sales Copy",
    "Email Copy",
    "Social Media Copywriting",
    "Press Releases",
    "UX Writing",
    "eLearning Content Development",
    "Technical Writing",
    "Handwriting",
    "Translation",
    "Localization",
    "Transcription",
    "Interpretation",
    "Business, Finance & Law",
    "Health & Medical",
    "Internet & Technology",
    "News & Politics",
    "Marketing",
    "Real Estate"
  ],
  "Music & Audio": [
    "Music Producers",
    "Composers",
    "Singers & Vocalists",
    "Session Musicians",
    "Songwriting",
    "Jingles & Intros",
    "Custom Songs",
    "24hr Turnaround",
    "Female Voice Over",
    "Male Voice Over",
    "French Voice Over",
    "German Voice Over",
    "Mixing & Mastering",
    "Audio Editing",
    "Vocal Tuning",
    "Podcast Production",
    "Audiobook Production",
    "Audio Ads Production",
    "Voice Synthesis & AI",
    "DJ Drops & Tags",
    "DJ Mixing",
    "Remixing",
    "Sound Design",
    "Meditation Music",
    "Audio Logo & Sonic Branding",
    "Custom Patches & Samples",
    "Audio Plugin Development",
    "Online Music Lessons",
    "Music Transcription",
    "Music & Audio Consultation"
  ],
  "Business": [
    "Business Formation & Registration",
    "Market Research",
    "Business Plans",
    "Business Consulting",
    "HR Consulting",
    "AI Consulting",
    "Virtual Assistant",
    "Project Management",
    "Software Management",
    "E-Commerce Management",
    "Supply Chain Management",
    "Customs & Tariff Advisory",
    "Event Management",
    "Product Management",
    "Intellectual Property Management",
    "Legal Documents & Contracts",
    "Legal Research",
    "General Legal Advice",
    "Sales",
    "Customer Experience Management (CXM)",
    "Lead Generation",
    "GTM Engineering",
    "Customer Service",
    "Data Visualization",
    "Data Analytics",
    "Data Scraping",
    "Presentations",
    "Online Investigations",
    "Sustainability Consulting",
    "Game Concept Design",
    "Other"
  ],
  "Finance": [
    "Fractional CFO Services",
    "Financial Reporting",
    "Bookkeeping",
    "Payroll Management",
    "Due Diligence",
    "Valuation",
    "Mergers & Acquisitions Advisory",
    "Corporate Finance Strategy",
    "Tax Returns",
    "Tax Identification Services",
    "Tax Planning",
    "Tax Compliance",
    "Tax Exemptions",
    "Budgeting and Forecasting",
    "Financial Modeling",
    "Cost Analysis",
    "Stock Analysis",
    "Personal Budget Management",
    "Investments Advisory",
    "Online Trading Lessons",
    "Retirement advisory",
    "Financial Coaching",
    "Insurance Advisory",
    "Investors Sourcing",
    "Funding Pitch Presentations",
    "Fundraising Consultation",
    "Mortgage Advisory",
    "Loan Advisory",
    "Credit Score Advisory",
    "Bank Account Opening"
  ],
  "AI Services": [
    "AI Mobile Apps",
    "AI Websites & Software",
    "AI Chatbot",
    "AI Integrations",
    "AI Agents",
    "AI Fine-Tuning",
    "AI Technology Consulting",
    "Data Science & ML",
    "Data Analytics",
    "Data Visualization",
    "AI Avatar Design",
    "ComfyUI Workflow Creation",
    "Midjourney Artists",
    "Stable Diffusion Artists",
    "All AI Art Services",
    "AI Consulting",
    "AI Strategy",
    "AI Lessons",
    "AI Music Videos",
    "AI Video Avatars",
    "AI UGC",
    "Voice Synthesis & AI",
    "Text to Speech",
    "AI Content Editing",
    "Custom Writing Prompts"
  ],
  "Personal Growth": [
    "Career Counseling",
    "Life Coaching",
    "Online Tutoring",
    "Language Lessons",
    "Generative AI Lessons",
    "Astrology & Psychics",
    "Arts & Crafts",
    "Tabletop Games",
    "Puzzle & Game Creation",
    "Cosplay Creation",
    "Traveling",
    "Collectibles",
    "Modeling & Acting",
    "Styling & Beauty",
    "Trend Forecasting",
    "Fitness",
    "Nutrition",
    "Wellness",
    "Game Coaching",
    "Marvel Rivals Coaching",
    "eSports Management & Strategy",
    "Game Matchmaking",
    "Ingame Creation",
    "Game Testing & Feedback",
    "Game Recordings & Guides",
    "Family & Genealogy",
    "Cosmetics Formulation",
    "Greeting Cards & Videos",
    "Embroidery Digitizing",
    "Other"
  ],
  "Consulting": [
    "Legal Consulting",
    "Business Consulting",
    "HR Consulting",
    "AI Consulting",
    "Business Plans",
    "E-commerce Consulting",
    "Marketing Strategy",
    "Content Strategy",
    "Social Media Strategy",
    "Influencers Strategy",
    "Video Marketing Consulting",
    "SEM Strategy",
    "PR Strategy",
    "Data Analytics Consulting",
    "Databases Consulting",
    "Data Visualization Consulting",
    "Career Counseling",
    "Life Coaching",
    "Game Coaching",
    "Styling & Beauty Advice",
    "Travel Advice",
    "Nutrition Coaching",
    "Mindfulness Coaching",
    "Traveling",
    "AI Technology Consulting",
    "Website Consulting",
    "Mobile App Consulting",
    "Game Development Consulting",
    "Software Development Consulting",
    "Cybersecurity Consulting",
    "Marketing Mentorship",
    "Design Mentorship",
    "Writing Mentorship",
    "Video Mentorship",
    "Music Mentorship"
  ],
  "Data": [
    "Machine Learning",
    "Computer Vision",
    "NLP",
    "Deep Learning",
    "Generative Models",
    "Time Series Analysis",
    "Data Analytics",
    "Data Visualization",
    "Data Tagging & Annotation",
    "Dashboards",
    "Data Entry",
    "Data Typing",
    "Data Scraping",
    "Data Formatting",
    "Data Cleaning",
    "Data Enrichment",
    "Data Processing",
    "Data Governance & Protection",
    "Databases",
    "Data Engineering"
  ],
  "Photography": [
    "Product Photographers",
    "Food Photographers",
    "Lifestyle & Fashion Photographers",
    "Portrait Photographers",
    "Event Photographers",
    "Real Estate Photographers",
    "Scenic Photographers",
    "Drone Photographers",
    "Photographers in New York",
    "Photographers in Los Angeles",
    "Photographers in London",
    "Photographers in Paris",
    "All Cities",
    "Photo Preset Creation",
    "Other"
  ]
};
const categories=Object.keys(subcategories);
type Pack={name:string;description:string;price:string;deliveryDays:string;revisions:string};
const initialPackages:Pack[]=[{name:"Basic",description:"",price:"",deliveryDays:"3",revisions:"1"},{name:"Standard",description:"",price:"",deliveryDays:"5",revisions:"2"},{name:"Premium",description:"",price:"",deliveryDays:"7",revisions:"3"}];
const suggestedTags:Record<string,string[]>={
 "Graphics & Design":["design","branding","creative","professional","custom"],"Programming & Tech":["website","development","coding","responsive","technology"],"Digital Marketing":["marketing","seo","social media","growth","campaign"],"Video & Animation":["video","editing","animation","professional","content"],"Writing & Translation":["writing","content","translation","proofreading","copywriting"],"Music & Audio":["audio","music","voice over","mixing","production"],"Business":["business","consulting","strategy","management","professional"],"Finance":["finance","accounting","bookkeeping","planning","analysis"],"AI Services":["ai","automation","chatbot","machine learning","consulting"],"Personal Growth":["coaching","growth","lessons","wellness","advice"],"Consulting":["consulting","strategy","advice","business","expert"],"Data":["data","analytics","machine learning","database","visualization"],"Photography":["photography","professional","editing","portrait","product"]
};

async function compressServiceImage(file:File){
 if(!["image/png","image/jpeg","image/jpg","image/webp"].includes(file.type.toLowerCase()))throw new Error(`${file.name} must be a PNG, JPG, JPEG or WebP image.`);
 if(file.size>40*1024*1024)throw new Error(`${file.name} is larger than 40 MB. Please choose a smaller original image.`);
 if(file.size<=1500*1024){const bitmap=await createImageBitmap(file);if(bitmap.width<=2400&&bitmap.height<=2400){bitmap.close();return file}bitmap.close()}
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext("2d");if(!context){bitmap.close();throw new Error(`Unable to prepare ${file.name}.`)}context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.84,blob:Blob|null=null;do{blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",quality));quality-=.08}while(blob&&blob.size>1500*1024&&quality>=.52);if(!blob)throw new Error(`Unable to compress ${file.name}.`);return new File([blob],file.name.replace(/\.[^.]+$/,"")+".webp",{type:"image/webp",lastModified:Date.now()});
}

export default function SellerListingForm({onClose}:{onClose:()=>void}){
 const[step,setStep]=useState(1);const[titleRest,setTitleRest]=useState("");const title=titleRest?TITLE_PREFIX+titleRest:"";const[description,setDescription]=useState("");const[category,setCategory]=useState(categories[0]);const[subcategory,setSubcategory]=useState(subcategories[categories[0]][0]);const[tags,setTags]=useState("");const[requirements,setRequirements]=useState("");const[packages,setPackages]=useState(initialPackages);const[packageEnabled,setPackageEnabled]=useState([true,true,true]);const[photos,setPhotos]=useState<File[]>([]);const[video,setVideo]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[submitted,setSubmitted]=useState(false);
 const activePackages=packages.filter((_,index)=>packageEnabled[index]);const validDetails=title.trim().length>=10&&description.trim().length>=50&&Boolean(category)&&Boolean(subcategory);const validPackages=activePackages.every(p=>p.description.trim().length>=10&&p.description.trim().length<=1000&&Number(p.price)>=0.5&&Number(p.deliveryDays)>=1&&(Number(p.revisions)>=0||Number(p.revisions)===-1));const photoPreviews=useMemo(()=>photos.map(file=>URL.createObjectURL(file)),[photos]);
 const updatePack=(index:number,key:keyof Pack,value:string)=>setPackages(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));
 const continueStep=()=>{if(step===1&&!validDetails){const missing=[];if(title.trim().length<10)missing.push("a title of at least 10 characters");if(description.trim().length<50)missing.push("a description of at least 50 characters");if(!category||!subcategory)missing.push("a category and subcategory");setNotice(`Please add ${missing.join(", ")} before continuing.`);return}if(step===2&&!validPackages){const tooLong=activePackages.filter(p=>p.description.trim().length>1000).map(p=>p.name);if(tooLong.length){setNotice(`${tooLong.join(" and ")} package descriptions must be 1,000 characters or fewer.`);return}const incomplete=activePackages.filter(p=>p.description.trim().length<10||Number(p.price)<0.5||Number(p.deliveryDays)<1).map(p=>p.name);setNotice(`Complete the ${incomplete.join(" and ")} package: description must be at least 10 characters and price must be at least €0.50.`);return}setNotice("");setStep(step+1)};
 const uploadFile=(file:File,path:string,label:string)=>new Promise<string>((resolve,reject)=>{const task=uploadBytesResumable(ref(getClientStorage(),path),file,{contentType:file.type});const timer=setTimeout(()=>{task.cancel();reject(new Error(`${label} upload timed out. Check your connection and try again.`))},120000);task.on("state_changed",snapshot=>setNotice(`${label}: ${Math.round(snapshot.bytesTransferred/snapshot.totalBytes*100)}% uploaded`),error=>{clearTimeout(timer);reject(error)},async()=>{clearTimeout(timer);try{resolve(await getDownloadURL(task.snapshot.ref))}catch(error){reject(error)}})});
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;const auth=getClientAuth();if(!auth.currentUser){setNotice("Please sign in with your email code before submitting a service.");return}if(!validDetails||!validPackages){setNotice("Please complete all required listing and package fields.");return}setBusy(true);setNotice("Preparing your service…");try{const uid=auth.currentUser.uid;const stamp=Date.now();const photoUrls:string[]=[];for(let index=0;index<photos.length;index++)photoUrls.push(await uploadFile(photos[index],`listings/${uid}/${stamp}/photo-${index}-${photos[index].name}`,`Photo ${index+1} of ${photos.length}`));let videoUrl:string|undefined;if(video)videoUrl=await uploadFile(video,`listings/${uid}/${stamp}/video-${video.name}`,"Video");setNotice("Saving your service for administrator review…");const token=await auth.currentUser.getIdToken(true);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);const response=await fetch("/api/listings",{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({title:title.trim(),description:description.trim(),category,subcategory,tags:tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,5),requirements:requirements.trim(),priceCents:Math.round(Number(packages[0].price)*100),deliveryDays:Number(packages[0].deliveryDays),revisions:Number(packages[0].revisions),photoUrls,videoUrl,packages:activePackages.map(p=>({name:p.name,description:p.description.trim(),priceCents:Math.round(Number(p.price)*100),deliveryDays:Number(p.deliveryDays),revisions:Number(p.revisions)}))})});clearTimeout(timer);const text=await response.text();let data:{id?:string;error?:string;listingFeeRequired?:boolean;listingCreditBalance?:number}={};try{data=text?JSON.parse(text):{}}catch{throw new Error(`Listing service returned an invalid response (${response.status})`)}if(!response.ok)throw new Error(data.error||"Unable to submit listing");if(data.listingFeeRequired&&data.id){setNotice("Redirecting to pay 2 USDT or 2 USDC for five listing credits…");const checkoutResponse=await fetch("/api/stripe/checkout",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({purpose:"listing-credits",listingId:data.id})});const checkoutText=await checkoutResponse.text();let checkout:{url?:string;error?:string}={};try{checkout=checkoutText?JSON.parse(checkoutText):{}}catch{throw new Error("Stripe checkout returned an invalid response")};if(!checkoutResponse.ok||!checkout.url)throw new Error(checkout.error||"Unable to open Stripe checkout");window.location.assign(checkout.url);return}setSubmitted(true);setNotice(data.listingCreditBalance?`Listing submitted for administrator approval. You have ${data.listingCreditBalance} listing credits remaining.`:"Listing submitted for administrator approval. Track it under Seller → My services.");}catch(error){setNotice(error instanceof DOMException&&error.name==="AbortError"?"Saving timed out. Please try again.":error instanceof Error?error.message:"Unable to submit listing");}finally{setBusy(false)}}
 if(submitted)return <div className="listingBackdrop"><div className="listingModal listingSuccess"><button className="listingClose" onClick={onClose}>×</button><span>✓</span><h2>Service submitted</h2><p>{notice}</p><button className="primary" onClick={onClose}>Return to seller dashboard</button></div></div>;
 return <div className="listingBackdrop" onMouseDown={onClose}><form className="listingModal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="listingClose" onClick={onClose}>×</button><div className="listingHeading"><div><small>SELLER LISTING</small><h2>Create a service</h2></div><b>Step {step} of 4</b></div><div className="listingProgress"><i style={{width:`${step*25}%`}}/></div>
 {step===1&&<div className="listingStep"><h3>Service overview</h3><label>Service title <span>{title.length}/100</span><div className="titlePrefixField"><span className="titlePrefixLock" aria-hidden="true">I will</span><input id="serviceTitleInput" value={titleRest} maxLength={100-TITLE_PREFIX.length} onChange={e=>setTitleRest(e.target.value)} placeholder="design a professional brand identity"/></div></label><div className="listingTwo"><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory(subcategories[e.target.value][0]);setTags("")}}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Subcategory<select value={subcategory} onChange={e=>setSubcategory(e.target.value)}>{subcategories[category].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Full gig description <span>{description.length}/5000</span><RichTextToolbar textareaId="serviceDescriptionInput" value={description} onChange={setDescription}/><textarea id="serviceDescriptionInput" rows={10} minLength={50} maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explain what you will deliver, your process, experience and what makes your service different…"/></label><label>Search tags <small>Up to five, separated by commas</small><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="logo, branding, minimalist, business"/></label><div className="suggestedTags"><span>Suggested tags</span>{suggestedTags[category].map(tag=><button type="button" key={tag} onClick={()=>{const next=[...new Set([...tags.split(",").map(x=>x.trim()).filter(Boolean),tag])].slice(0,5);setTags(next.join(", "))}}>{tag}</button>)}<button type="button" className="copyTags" onClick={async()=>{const value=suggestedTags[category].slice(0,5).join(", ");setTags(value);await navigator.clipboard?.writeText(value);setNotice("Suggested tags copied and added.")}}>Copy all</button></div></div>}
 {step===2&&<div className="listingStep"><h3>Packages and delivery</h3><p className="packageHelp">Basic is required. Turn off Standard or Premium if you want fewer packages.</p><div className="packageEditor">{packages.map((pack,index)=><section key={pack.name} className={!packageEnabled[index]?"packageOff":""}><div className="packageTitle"><b>{pack.name}</b>{index===0?<small>Required</small>:<label className="packageToggle"><input type="checkbox" checked={packageEnabled[index]} onChange={e=>setPackageEnabled(items=>items.map((value,i)=>i===index?e.target.checked:value))}/><i/><span>{packageEnabled[index]?"On":"Off"}</span></label>}</div>{packageEnabled[index]?<><label>Package description <small>{pack.description.trim().length}/1000</small><textarea rows={4} minLength={10} maxLength={1000} value={pack.description} onChange={e=>updatePack(index,"description",e.target.value)} placeholder={`What is included in ${pack.name}?`}/></label><label>Price (€)<input type="number" min="0.50" step="0.01" value={pack.price} onChange={e=>updatePack(index,"price",e.target.value)} placeholder="Minimum €0.50"/></label><label>Delivery time<select value={pack.deliveryDays} onChange={e=>updatePack(index,"deliveryDays",e.target.value)}>{[1,2,3,5,7,10,14,21,30].map(x=><option key={x} value={x}>{x} day{x>1?"s":""}</option>)}</select></label><label>Revisions<select value={pack.revisions} onChange={e=>updatePack(index,"revisions",e.target.value)}>{[0,1,2,3,4,5,6,7,8,9,10].map(x=><option key={x} value={x}>{x===0?"No revisions":`${x} revision${x===1?"":"s"}`}</option>)}<option value="-1">Unlimited revisions</option></select></label></>:<p className="packageDisabled">This package will not appear on your listing.</p>}</section>)}</div></div>}
 {step===3&&<div className="listingStep"><h3>Gallery and buyer requirements</h3><label className="mediaUpload">Service photos <small>Maximum two. Large photos are automatically resized and compressed.</small><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={async e=>{const chosen=[...(e.target.files||[])].slice(0,2);if(!chosen.length)return;setNotice("Optimising your service photos…");try{const compressed=await Promise.all(chosen.map(compressServiceImage));setPhotos(compressed);const before=chosen.reduce((total,file)=>total+file.size,0),after=compressed.reduce((total,file)=>total+file.size,0);setNotice(`Photos ready: ${(before/1048576).toFixed(1)} MB compressed to ${(after/1048576).toFixed(1)} MB.`)}catch(error){setNotice(error instanceof Error?error.message:"Unable to compress the selected photos.")}}}/>{photos.length?<div className="mediaPreview">{photoPreviews.map((url,i)=><img key={url} src={url} alt={`Service preview ${i+1}`}/>)}</div>:<b>Choose up to two photos</b>}</label><label className="mediaUpload">Service video <small>Optional, maximum one video, 200 MB</small><input type="file" accept="video/*" onChange={e=>{const file=e.target.files?.[0]||null;if(file&&file.size>200*1024*1024){setNotice("Video must be smaller than 200 MB.");return}setVideo(file)}}/><b>{video?.name||"Choose one video"}</b></label><label>Information required from the buyer<textarea rows={6} value={requirements} maxLength={2000} onChange={e=>setRequirements(e.target.value)} placeholder="What should the buyer send before you begin?"/></label></div>}
 {step===4&&<div className="listingStep"><h3>Preview and submit</h3><article className="listingPreview">{photoPreviews[0]?<img src={photoPreviews[0]} alt="Main service image"/>:<div>Upload a main service image</div>}<small>{category} · {subcategory}</small><h2>{title||"Your service title"}</h2><p dangerouslySetInnerHTML={{__html:description?renderRichText(description):"Your full service description will appear here."}}/><div className="previewPackages">{activePackages.map(p=><span key={p.name}><b>{p.name}</b><small>{p.deliveryDays} days</small><strong>€{Number(p.price||0).toFixed(2)}</strong></span>)}</div></article><label className="listingConfirm"><input type="checkbox" required/> I confirm this service is accurate and follows SaharaSnow’s marketplace rules.</label></div>}
 {notice&&<p className="listingNotice" role="alert">{notice}</p>}<div className="listingActions">{step>1&&<button type="button" onClick={()=>{setNotice("");setStep(step-1)}}>Back</button>}{step<4?<button type="button" className="primary" onClick={continueStep}>Continue</button>:<button className="primary" disabled={busy}>{busy?"Uploading and submitting…":"Submit for approval"}</button>}</div></form></div>
}
