import {FieldValue}from"firebase-admin/firestore";
import {NextRequest,NextResponse}from"next/server";
import {z}from"zod";
import {db}from"@/lib/firebase-admin";
import {notifyAdminInApp,notifyUser}from"@/lib/notifications";
import {postSystemMessage}from"@/lib/messaging";
import {publicError,userFromRequest}from"@/lib/server";
export const runtime="nodejs";
const schema=z.object({orderId:z.string().min(1),message:z.string().trim().min(10).max(3000)});
export async function POST(req:NextRequest){try{const user=await userFromRequest(req),body=schema.parse(await req.json());const ref=db.collection("orders").doc(body.orderId);let order:any;await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw Error("Order not found.");order=snap.data()||{};if(String(order.buyerId)!==user.uid)throw Error("Only the buyer can request a revision.");if(String(order.status)!=="delivered")throw Error("Revisions can only be requested on a delivered order.");tx.set(ref,{status:"in-progress",deliveryStatus:"revision-requested",revisionRequestedAt:FieldValue.serverTimestamp(),revisionMessage:body.message,clearanceStartsAt:FieldValue.delete(),clearanceEndsAt:FieldValue.delete(),disputeWindowEndsAt:FieldValue.delete(),disputeDeadline:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp()},{merge:true});});await ref.collection("events").add({type:"revision_requested",message:body.message,actorId:user.uid,createdAt:FieldValue.serverTimestamp()});const number=String(order.orderNumber||body.orderId);await notifyUser({userId:String(order.sellerId),type:"revision_requested",eventId:`${body.orderId}_revision_${Date.now()}`,title:`Revision requested for order #${number}`,message:`The buyer requested changes: "${body.message}"`,link:`/?order=${body.orderId}`,email:true});await notifyAdminInApp({type:"order_revision",eventId:body.orderId,title:`Revision requested for order #${number}`,message:"The buyer sent the order back for changes before the dispute window closed.",link:"/admin"});const sellerId=String(order.sellerId||"");if(sellerId)await postSystemMessage({buyerId:user.uid,sellerId,orderId:body.orderId,text:`✏️ Revision requested for order #${number}: "${body.message}"`});return NextResponse.json({ok:true});}catch(e){const x=e instanceof z.ZodError?{message:"Please describe the requested changes (minimum 10 characters).",status:400}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
