import { NextRequest, NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { db } from "@/lib/firebase-admin";
import { notifyAdminInApp, notifyUser } from "@/lib/notifications";
import { publicError, userFromRequest } from "@/lib/server";
import { cryptoOrderNumber, resolveCryptoDeposit } from "@/lib/crypto-deposit";
export const runtime="nodejs";
export const dynamic="force-dynamic";
const createSchema=z.object({sellerId:z.string().min(1),title:z.string().trim().min(3).max(160),description:z.string().trim().max(2000).default(""),amountCents:z.number().int().min(500).max(100000000),paymentCurrency:z.enum(["USDT","USDC"]).default("USDT")});
const submittedSchema=z.object({invoiceId:z.string().min(1),txHash:z.string().trim().min(16).max(256)});
export async function POST(req:NextRequest){try{const user=await userFromRequest(req),body=createSchema.parse(await req.json());if(user.uid===body.sellerId)return NextResponse.json({error:"Choose a different seller."},{status:400});const seller=await db.collection("users").doc(body.sellerId).get();if(!seller.exists)return NextResponse.json({error:"Seller not found."},{status:404});const invoiceRef=db.collection("customInvoices").doc(),currency=body.paymentCurrency,{network,address:depositAddress}=resolveCryptoDeposit(currency);if(!depositAddress)return NextResponse.json({error:"USDC payments are not configured yet. Add USDC_BEP20_DEPOSIT_ADDRESS in the server environment."},{status:503});const paymentOrderNumber=cryptoOrderNumber(invoiceRef.id,currency);await invoiceRef.set({purpose:"service-order",buyerId:user.uid,sellerId:body.sellerId,title:body.title,description:body.description,amountCents:body.amountCents,serviceCents:body.amountCents,sellerNetCents:body.amountCents,platformFeeCents:0,stripeMarkupCents:0,checkoutTotalCents:body.amountCents,currency, paymentCurrency:currency,network,depositAddress,orderNumber:paymentOrderNumber,status:"awaiting-crypto-payment",paymentMethod:currency==="USDT"?"crypto-usdt-trc20":"usdc-bep20",createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return NextResponse.json({invoiceId:invoiceRef.id,orderNumber:paymentOrderNumber,amountCents:body.amountCents,currency,network,depositAddress,serviceCents:body.amountCents,checkoutTotalCents:body.amountCents});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PUT(req:NextRequest){try{const user=await userFromRequest(req),{invoiceId,txHash}=submittedSchema.parse(await req.json()),normalizedTxHash=txHash.trim().toLowerCase(),invoiceRef=db.collection("customInvoices").doc(invoiceId),snap=await invoiceRef.get();if(!snap.exists)return NextResponse.json({error:"Invoice not found."},{status:404});const invoice=snap.data()||{};if(String(invoice.buyerId)!==user.uid)return NextResponse.json({error:"Forbidden"},{status:403});if(!["awaiting-crypto-payment","payment-submitted"].includes(String(invoice.status)))return NextResponse.json({error:"This invoice can no longer accept a payment reference."},{status:400});const existing=await db.collection("customInvoices").where("txHashNormalized","==",normalizedTxHash).limit(1).get();if(!existing.empty&&existing.docs.some(d=>d.id!==invoiceId))return NextResponse.json({error:"This transaction hash has already been used for another payment."},{status:409});await invoiceRef.set({status:"payment-submitted",txHash:txHash.trim(),txHashNormalized:normalizedTxHash,cryptoSubmittedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});const no=String(invoice.orderNumber||cryptoOrderNumber(invoiceId,String(invoice.paymentCurrency||"USDT")));await notifyAdminInApp({type:"crypto_payment_submitted",eventId:invoiceId,title:`${String(invoice.paymentCurrency||"USDT")} payment submitted — ${no}`,message:`${no} has a submitted ${String(invoice.network||"")} transaction hash. Verify it in Admin Earnings and approve the payment to assign the earning to the dedicated seller.`,link:"/admin/financials"});await notifyUser({userId:user.uid,type:"crypto_payment_submitted",eventId:invoiceId,title:`Payment submitted — ${no}`,message:`Your ${String(invoice.paymentCurrency||"USDT")} payment is awaiting administrator approval.`,link:"/?inbox=1"});return NextResponse.json({ok:true,status:"payment-submitted",orderNumber:no});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
