import {NextRequest,NextResponse} from "next/server";
import {FieldValue} from "firebase-admin/firestore";
import {z} from "zod";
import {db} from "@/lib/firebase-admin";
import {notifyUser} from "@/lib/notifications";
import {publicError,userFromRequest} from "@/lib/server";

const submitSchema=z.object({transactionHash:z.string().trim().min(8).max(300),currency:z.enum(["USDT","USDC"]),amount:z.number().positive().max(1000000),purpose:z.string().trim().max(100).optional(),orderId:z.string().trim().min(1).max(200).optional()});
type Stage="submitted"|"approved"|"rejected";
type OrderUsers={buyerId:string;sellerId:string;number:string};

async function getOrderUsers(orderId:string):Promise<OrderUsers|null>{const snap=await db.collection("orders").doc(orderId).get();if(!snap.exists)return null;const order=snap.data()||{};return {buyerId:String(order.buyerId||""),sellerId:String(order.sellerId||""),number:String(order.orderNumber||orderId)};}
async function notifyOrderParticipants(orderId:string,stage:Stage,currency:string,amount:number):Promise<void>{const users=await getOrderUsers(orderId);if(!users)return;const amountText=`${amount} ${currency}`;const link=`/?order=${encodeURIComponent(orderId)}`;const submitted=stage==="submitted";const approved=stage==="approved";const jobs:Promise<unknown>[]=[];if(users.buyerId)jobs.push(notifyUser({userId:users.buyerId,type:`crypto_payment_${stage}`,eventId:`${orderId}_${stage}`,title:submitted?"Crypto payment submitted":approved?"Crypto payment approved":"Crypto payment rejected",message:submitted?`Your ${amountText} payment for order #${users.number} is awaiting administrator approval.`:approved?`Your ${amountText} payment for order #${users.number} was approved. The order is now active.`:`Your ${amountText} payment for order #${users.number} was rejected. Please review your payment and submit a valid transaction.`,link,email:true}));if(users.sellerId)jobs.push(notifyUser({userId:users.sellerId,type:`crypto_payment_${stage}_seller`,eventId:`${orderId}_${stage}`,title:submitted?"Buyer submitted crypto payment":approved?"Crypto payment approved":"Crypto payment rejected",message:submitted?`The buyer submitted ${amountText} for order #${users.number}. The payment is awaiting administrator approval.`:approved?`The ${amountText} payment for order #${users.number} was approved. You can now proceed with the order.`:`The crypto payment for order #${users.number} was rejected. The order remains unpaid.`,link,email:true}));await Promise.all(jobs);}

export async function POST(req:NextRequest){try{const user=await userFromRequest(req);const body=submitSchema.parse(await req.json());const hash=body.transactionHash.toLowerCase();const ref=db.collection("cryptoPayments").doc();if(body.orderId){const order=await getOrderUsers(body.orderId);if(!order)throw new Error("Order not found.");if(order.buyerId!==user.uid)throw new Error("Only the buyer can submit payment for this order.");}await db.runTransaction(async tx=>{const duplicate=await tx.get(db.collection("cryptoPayments").where("transactionHash","==",hash).limit(1));if(!duplicate.empty)throw new Error("This transaction hash has already been submitted.");tx.set(ref,{userId:user.uid,userEmail:user.email||"",transactionHash:hash,currency:body.currency,amount:body.amount,purpose:body.orderId?"order":body.purpose||"deposit",orderId:body.orderId||null,status:"pending",submittedAt:FieldValue.serverTimestamp(),approvedAt:null,approvedBy:null,rejectedAt:null,rejectedBy:null});});if(body.orderId)await notifyOrderParticipants(body.orderId,"submitted",body.currency,body.amount);else await notifyUser({userId:user.uid,type:"crypto_deposit_submitted",eventId:ref.id,title:"Crypto payment submitted",message:`Your ${body.amount} ${body.currency} deposit is awaiting administrator approval.`,link:"/?seller=1",email:true});return NextResponse.json({ok:true,id:ref.id,status:"pending",message:"Payment submitted for administrator approval."});}catch(e){const x=e instanceof z.ZodError?{message:"Invalid payment submission.",status:400}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}

export async function GET(req:NextRequest){try{const user=await userFromRequest(req);const admin=(await db.collection("users").doc(user.uid).get()).data()||{};if(admin.role!=="admin")return NextResponse.json({error:"Administrator access required."},{status:403});const status=req.nextUrl.searchParams.get("status")||"pending";const snap=await db.collection("cryptoPayments").where("status","==",status).limit(200).get();return NextResponse.json({payments:snap.docs.map(d=>({id:d.id,...d.data()}))});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}

export async function PATCH(req:NextRequest){try{const adminUser=await userFromRequest(req);const admin=(await db.collection("users").doc(adminUser.uid).get()).data()||{};if(admin.role!=="admin")return NextResponse.json({error:"Administrator access required."},{status:403});const body=z.object({id:z.string().min(1),action:z.enum(["approve","reject"])}).parse(await req.json());const ref=db.collection("cryptoPayments").doc(body.id);let orderId="";let currency="";let amount=0;let stage:Stage|undefined;let result:Record<string,unknown>={};await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Payment not found.");const payment=snap.data()||{};if(payment.status!=="pending")throw new Error("This payment has already been processed.");const isOrder=String(payment.purpose)==="order"&&Boolean(payment.orderId);currency=String(payment.currency||"");amount=Number(payment.amount||0);if(body.action==="approve"){if(isOrder){orderId=String(payment.orderId);const orderRef=db.collection("orders").doc(orderId);const orderSnap=await tx.get(orderRef);if(!orderSnap.exists)throw new Error("Order not found.");tx.update(orderRef,{status:"in-progress",paymentStatus:"approved",cryptoPaymentId:ref.id,paidAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});tx.update(ref,{status:"approved",approvedAt:FieldValue.serverTimestamp(),approvedBy:adminUser.uid});stage="approved";result={ok:true,status:"approved",orderId};}else{const userRef=db.collection("users").doc(String(payment.userId));const userSnap=await tx.get(userRef);if(!userSnap.exists)throw new Error("Payment user not found.");const data=userSnap.data()||{};const current=Math.max(0,Number(data.balance||0));tx.update(userRef,{balance:current+amount,updatedAt:FieldValue.serverTimestamp()});tx.update(ref,{status:"approved",approvedAt:FieldValue.serverTimestamp(),approvedBy:adminUser.uid});result={ok:true,status:"approved",creditedAmount:amount};}}else{if(isOrder){orderId=String(payment.orderId);tx.update(db.collection("orders").doc(orderId),{status:"awaiting-crypto-payment",paymentStatus:"rejected",updatedAt:FieldValue.serverTimestamp()});stage="rejected";}tx.update(ref,{status:"rejected",rejectedAt:FieldValue.serverTimestamp(),rejectedBy:adminUser.uid});result={ok:true,status:"rejected"};}});if(orderId&&stage)await notifyOrderParticipants(orderId,stage,currency,amount);return NextResponse.json(result);}catch(e){const x=e instanceof z.ZodError?{message:"Invalid payment action.",status:400}:publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
