import { FieldValue } from "firebase-admin/firestore";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/firebase-admin";
import { publicError, userFromRequest } from "@/lib/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type ReviewData = Record<string, unknown> & { id: string };

function timestampMillis(value: unknown): number { if (value && typeof value === "object" && "toMillis" in value) { const fn=(value as {toMillis?:unknown}).toMillis; if(typeof fn==="function") return Number(fn.call(value))||0; } return 0; }
function reviewerProfile(data:Record<string,unknown>){const first=String(data.firstName||"").trim();const last=String(data.lastName||"").trim();const name=[first,last].filter(Boolean).join(" ")||String(data.displayName||data.name||"SaharaSnow buyer");return {buyerName:name,buyerFirstName:first,buyerLastName:last,buyerProfileImageUrl:String(data.profileImageUrl||data.photoURL||data.photoUrl||""),buyerCountry:String(data.country||""),buyerCountryCode:String(data.countryCode||data.countryISO||data.countryIso||"").toUpperCase()};}

export async function GET(req: NextRequest) { try { const params=new URL(req.url).searchParams; const orderId=String(params.get("orderId")||""); if(orderId){const user=await userFromRequest(req);const orderSnap=await db.collection("orders").doc(orderId).get();if(!orderSnap.exists)return NextResponse.json({error:"Order not found"},{status:404});const order=orderSnap.data()||{};if(String(order.buyerId)!==user.uid)return NextResponse.json({error:"Not authorized"},{status:403});const reviewSnap=await db.collection("reviews").doc(orderId).get();return NextResponse.json({order:{id:orderId,sellerId:String(order.sellerId||""),status:String(order.status||"")},reviewed:reviewSnap.exists});}
 const sellerId=String(params.get("sellerId")||"");if(!sellerId)return NextResponse.json({error:"sellerId is required"},{status:400});const [snap,sellerSnap]=await Promise.all([db.collection("reviews").where("sellerId","==",sellerId).limit(500).get(),db.collection("users").doc(sellerId).get()]);const seller=sellerSnap.data()||{};const raw: ReviewData[]=snap.docs.map(d=>({id:d.id,...(d.data() as Record<string,unknown>)} as ReviewData));const buyerIds=[...new Set(raw.map(r=>String(r.buyerId||"")).filter(Boolean))];const buyerSnaps=await Promise.all(buyerIds.map(id=>db.collection("users").doc(id).get()));const buyers=new Map(buyerSnaps.filter(s=>s.exists).map(s=>[s.id,s.data()||{}]));const reviews:ReviewData[]=raw.map(r=>{const current=buyers.get(String(r.buyerId||""));const profile=current?reviewerProfile(current as Record<string,unknown>):{};return {...r,...profile};});reviews.sort((a,b)=>timestampMillis(b.createdAt)-timestampMillis(a.createdAt));let eligibleOrderIds:string[]=[];if(req.headers.get("authorization")){try{const user=await userFromRequest(req);const buyerOrders=await db.collection("orders").where("buyerId","==",user.uid).where("sellerId","==",sellerId).where("status","==","completed-released").limit(100).get();const reviewedIds=new Set(snap.docs.map(d=>d.id));eligibleOrderIds=buyerOrders.docs.filter(d=>!reviewedIds.has(d.id)).map(d=>d.id);}catch{eligibleOrderIds=[];}}const count=Number(seller.reviewCount||0);const sum=Number(seller.reviewRatingSum||0);return NextResponse.json({reviews,summary:{count,average:count?Number((sum/count).toFixed(1)):0},eligibleOrderIds}); } catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});} }

export async function POST(req: NextRequest) { try { const user=await userFromRequest(req);const b=await req.json();const orderId=String(b.orderId||"");const sellerId=String(b.sellerId||"");const rating=Number(b.rating);const text=String(b.text||"").trim();if(!orderId||!sellerId||!Number.isInteger(rating)||rating<1||rating>5||text.length<5||text.length>2000)return NextResponse.json({error:"Invalid review"},{status:400});const order=await db.collection("orders").doc(orderId).get();const o=order.data()||{};if(!order.exists||String(o.buyerId)!==user.uid||String(o.sellerId)!==sellerId||String(o.status)!=="completed-released")return NextResponse.json({error:"Only the buyer of a released order can review it"},{status:403});const [sellerRef,buyerSnap]=[db.collection("users").doc(sellerId),await db.collection("users").doc(user.uid).get()];const reviewRef=db.collection("reviews").doc(orderId);const profile=reviewerProfile((buyerSnap.data()||{}) as Record<string,unknown>);let reviewId="";await db.runTransaction(async tx=>{const existing=await tx.get(reviewRef);if(existing.exists)throw new Error("This order already has a review");const sellerSnap=await tx.get(sellerRef);const seller=sellerSnap.data()||{};const nextCount=Number(seller.reviewCount||0)+1;const nextSum=Number(seller.reviewRatingSum||0)+rating;tx.create(reviewRef,{buyerId:user.uid,sellerId,orderId,listingId:String(o.listingId||""),rating,text,verifiedPurchase:true,...profile,createdAt:FieldValue.serverTimestamp()});tx.set(sellerRef,{reviewCount:nextCount,reviewRatingSum:nextSum,averageRating:Number((nextSum/nextCount).toFixed(1))},{merge:true});reviewId=reviewRef.id;});return NextResponse.json({ok:true,id:reviewId});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});} }
