import { FieldValue } from "firebase-admin/firestore";
import { NextRequest,NextResponse } from "next/server";
import { db } from "@/lib/firebase-admin";
import { publicError,userFromRequest } from "@/lib/server";
export const runtime="nodejs";
export const dynamic="force-dynamic";

export async function GET(req:NextRequest){try{const params=new URL(req.url).searchParams;const orderId=String(params.get("orderId")||"");if(orderId){const user=await userFromRequest(req);const orderSnap=await db.collection("orders").doc(orderId).get();if(!orderSnap.exists)return NextResponse.json({error:"Order not found"},{status:404});const order=orderSnap.data()||{};if(String(order.buyerId)!==user.uid)return NextResponse.json({error:"Not authorized"},{status:403});const reviewSnap=await db.collection("reviews").doc(orderId).get();return NextResponse.json({order:{id:orderId,sellerId:String(order.sellerId||""),status:String(order.status||"")},reviewed:reviewSnap.exists});}const sellerId=String(params.get("sellerId")||"");if(!sellerId)return NextResponse.json({error:"sellerId is required"},{status:400});const [snap,sellerSnap]=await Promise.all([db.collection("reviews").where("sellerId","==",sellerId).limit(500).get(),db.collection("users").doc(sellerId).get()]);const seller=sellerSnap.data()||{};const reviews=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const aa=a.createdAt?.toMillis?.()||0,bb=b.createdAt?.toMillis?.()||0;return bb-aa;});const count=Number(seller.reviewCount||0),sum=Number(seller.reviewRatingSum||0);return NextResponse.json({reviews,summary:{count,average:count?Number((sum/count).toFixed(1)):0}});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}

export async function POST(req:NextRequest){try{const user=await userFromRequest(req);const b=await req.json();const orderId=String(b.orderId||""),sellerId=String(b.sellerId||""),rating=Number(b.rating),text=String(b.text||"").trim();if(!orderId||!sellerId||!Number.isInteger(rating)||rating<1||rating>5||text.length<5||text.length>2000)return NextResponse.json({error:"Invalid review"},{status:400});const order=await db.collection("orders").doc(orderId).get();const o=order.data()||{};if(!order.exists||String(o.buyerId)!==user.uid||String(o.sellerId)!==sellerId||String(o.status)!=="completed-released")return NextResponse.json({error:"Only the buyer of a released order can review it"},{status:403});const sellerRef=db.collection("users").doc(sellerId),reviewRef=db.collection("reviews").doc(orderId);let reviewId="";await db.runTransaction(async tx=>{const existing=await tx.get(reviewRef);if(existing.exists)throw new Error("This order already has a review");const sellerSnap=await tx.get(sellerRef);const seller=sellerSnap.data()||{};const nextCount=Number(seller.reviewCount||0)+1;const nextSum=Number(seller.reviewRatingSum||0)+rating;tx.create(reviewRef,{buyerId:user.uid,sellerId,orderId,rating,text,verifiedPurchase:true,createdAt:FieldValue.serverTimestamp()});tx.set(sellerRef,{reviewCount:nextCount,reviewRatingSum:nextSum,averageRating:Number((nextSum/nextCount).toFixed(1))},{merge:true});reviewId=reviewRef.id;});return NextResponse.json({ok:true,id:reviewId});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
