"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {getClientAuth} from "@/lib/firebase-client";
type Payment={id:string;title?:string;amountCents?:number;totalCents?:number;txHash?:string;network?:string;source?:"invoice"|"order";packageName?:string;paymentCurrency?:string;paymentMethod?:string;status?:string;releaseAfterAt?:any};
const money=(p:Payment)=>`${(Number(p.amountCents??p.totalCents??0)/100).toFixed(2)} ${p.paymentCurrency||"USDT"}`;
const dateValue=(v:any)=>{if(!v)return "—";if(typeof v==="string")return new Date(v).toLocaleString();if(v.seconds)return new Date(Number(v.seconds)*1000).toLocaleString();return "—"};
export default function CryptoPaymentsPage(){const[items,setItems]=useState<Payment[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");const load=async()=>{try{setError("");const user=getClientAuth().currentUser;if(!user)throw new Error("Sign in with your administrator account.");const token=await user.getIdToken(true);const r=await fetch("/api/admin/crypto-payments",{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load payments.");setItems((j.payments||[]).filter((p:Payment)=>p.source==="order"))}catch(e){setError(e instanceof Error?e.message:"Could not load payments.")}};useEffect(()=>{const a=getClientAuth();return a.onAuthStateChanged(u=>{if(u)void load();else setError("Sign in with your administrator account.")})},[]);
const action=async(p:Payment,kind:"confirm"|"reject")=>{if(kind==="confirm"&&!window.confirm(`Mark ${money(p)} as RECEIVED? This starts the 5-day dispute window.`))return;const note=window.prompt(kind==="reject"?"Reason for rejection:":"Optional admin note:");if(note===null)return;try{setBusy(p.id);const user=getClientAuth().currentUser;if(!user)throw new Error("Sign in first.");const token=await user.getIdToken(true);const r=await fetch("/api/admin/crypto-payments",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({invoiceId:p.id,action:kind,note,source:"order"})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Action failed.");await load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}};
return <main style={{maxWidth:1100,margin:"0 auto",padding:32}}><header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:28}}><div><Link href="/admin">← Admin dashboard</Link><h1 style={{margin:"12px 0 4px"}}>◈ Crypto settlement</h1><p>Admin verifies the buyer transaction hash. Once marked received, the seller's USDT or USDC stays locked for 5 days. If there is no dispute, the system releases it automatically.</p></div><button onClick={()=>void load()}>Refresh</button></header>{error&&<p style={{padding:12,border:"1px solid #d33",borderRadius:8}}>{error}</p>}{items.length===0?<p>No crypto service payments are waiting.</p>:<div style={{display:"grid",gap:16}}>{items.map(p=><article key={p.id} style={{border:"1px solid #ddd",borderRadius:14,padding:20}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><h2 style={{marginTop:0}}>Service order</h2><p><b>{p.title||p.packageName||"Service payment"}</b></p><p>Amount: <b>{money(p)}</b></p><p>Network: {p.network||"—"}</p><p>Status: <b>{p.status==="crypto-received"?"RECEIVED — 5-day dispute window":"PAYMENT SUBMITTED — awaiting admin verification"}</b></p>{p.status==="crypto-received"&&<p>Automatic release after: <b>{dateValue(p.releaseAfterAt)}</b></p>}</div>{p.status==="payment-submitted"&&<div><button disabled={busy===p.id} onClick={()=>void action(p,"confirm")}>✓ Mark received</button><button disabled={busy===p.id} onClick={()=>void action(p,"reject")} style={{marginLeft:8}}>Reject</button></div>}</div><b>Transaction hash</b><code style={{display:"block",overflowWrap:"anywhere",padding:10,background:"#f5f5f5",borderRadius:8}}>{p.txHash||"—"}</code></article>)}</div>}</main>}
