import {NextRequest,NextResponse} from "next/server";
import {db} from "@/lib/firebase-admin";
import {publicError,userFromRequest} from "@/lib/server";
export const runtime="nodejs";export const dynamic="force-dynamic";
const pendingWithdrawalStatuses=new Set(["pending","pending-manual-payment","processing"]),paidWithdrawalStatuses=new Set(["paid","completed","processed","paid-out"]),releasedStatuses=new Set(["completed-released","released","completed"]),cryptoMethods=new Set(["crypto-usdt-trc20","usdt-trc20","usdc-bep20"]);
function cents(...v:unknown[]){for(const x of v){const n=Number(x);if(Number.isFinite(n)&&n!==0)return Math.round(n)}return 0}
async function assertAdmin(req:NextRequest){const token=await userFromRequest(req),email=String(token.email||"").toLowerCase(),allowed=String(process.env.SUPER_ADMIN_EMAIL||process.env.ADMIN_EMAIL||"").toLowerCase();if(!allowed||email!==allowed)throw new Error("FORBIDDEN");return token}
function addSeller(map:Map<string,any>,id:string){if(!map.has(id))map.set(id,{id,name:"",email:"",mode:"SELLER",totalEarningsCents:0,pendingEarningsCents:0,availableBalanceCents:0,usdtBalanceCents:0,usdcBalanceCents:0,paidWithdrawalsCents:0,pendingWithdrawalsCents:0});return map.get(id)}
export async function GET(req:NextRequest){try{await assertAdmin(req);const [users,orders,invoices,withdrawals]=await Promise.all([db.collection("users").limit(1000).get(),db.collection("orders").limit(5000).get(),db.collection("customInvoices").where("purpose","==","service-order").limit(5000).get(),db.collection("withdrawals").limit(2000).get()]);const sellers=new Map<string,any>();for(const d of users.docs){const x=d.data();sellers.set(d.id,{id:d.id,name:[x.firstName,x.lastName].filter(Boolean).join(" ")||String(x.name||x.displayName||""),email:String(x.email||""),mode:String(x.mode||"BUYING"),totalEarningsCents:0,pendingEarningsCents:0,availableBalanceCents:0,usdtBalanceCents:Number(x.usdtBalanceCents||0),usdcBalanceCents:Number(x.usdcBalanceCents||0),paidWithdrawalsCents:0,pendingWithdrawalsCents:0})}let grossCents=0,sellerEarningsCents=0,platformFeesCents=0,cryptoGrossCents=0,cryptoPendingCents=0,cryptoReleasedCents=0;
for(const d of orders.docs){const o=d.data(),status=String(o.status||"").toLowerCase(),isCrypto=cryptoMethods.has(String(o.paymentMethod||""));if(isCrypto){const gross=cents(o.serviceCents,o.amountCents,o.totalCents),net=cents(o.sellerNetCents,o.sellerEarningsCents,o.netCents)||gross;cryptoGrossCents+=gross;if(status==="crypto-received")cryptoPendingCents+=net;if(releasedStatuses.has(status))cryptoReleasedCents+=net;if(!["crypto-received",...releasedStatuses].includes(status))continue;const seller=addSeller(sellers,String(o.sellerId||""));if(!seller.id)continue;if(status==="crypto-received")seller.pendingEarningsCents+=net;else seller.totalEarningsCents+=net;}}
for(const d of invoices.docs){const i=d.data(),status=String(i.status||"").toLowerCase(),gross=cents(i.amountCents,i.serviceCents),net=cents(i.sellerNetCents,i.serviceCents,i.amountCents);if(status==="payment-submitted")cryptoGrossCents+=gross;if(status==="crypto-received"){cryptoGrossCents+=gross;cryptoPendingCents+=net}if(releasedStatuses.has(status)){cryptoGrossCents+=gross;cryptoReleasedCents+=net}if(!["crypto-received",...releasedStatuses].includes(status))continue;const sellerId=String(i.sellerId||"");if(!sellerId)continue;const seller=addSeller(sellers,sellerId);if(status==="crypto-received")seller.pendingEarningsCents+=net;else seller.totalEarningsCents+=net}
let pendingWithdrawalsCents=0,paidWithdrawalsCents=0;for(const d of withdrawals.docs){const w=d.data(),status=String(w.status||"").toLowerCase(),gross=cents(w.grossCents,w.amountCents,w.netCents),net=cents(w.netCents,w.amountCents,w.grossCents),sellerId=String(w.sellerId||w.userId||"");if(pendingWithdrawalStatuses.has(status))pendingWithdrawalsCents+=net;if(paidWithdrawalStatuses.has(status))paidWithdrawalsCents+=net;if(sellerId&&sellers.has(sellerId)){const s=sellers.get(sellerId);if(pendingWithdrawalStatuses.has(status))s.pendingWithdrawalsCents+=gross;if(paidWithdrawalStatuses.has(status))s.paidWithdrawalsCents+=gross}}
const rows=[...sellers.values()].map(s=>({...s,availableBalanceCents:Math.max(0,s.totalEarningsCents-s.paidWithdrawalsCents-s.pendingWithdrawalsCents)})).filter(x=>x.mode==="SELLER"||x.totalEarningsCents>0||x.pendingEarningsCents>0||x.usdtBalanceCents>0||x.usdcBalanceCents>0).sort((a,b)=>b.usdcBalanceCents+b.usdtBalanceCents-a.usdcBalanceCents-a.usdtBalanceCents||b.availableBalanceCents-a.availableBalanceCents);return NextResponse.json({grossCents,sellerEarningsCents,platformFeesCents,pendingWithdrawalsCents,paidWithdrawalsCents,cryptoGrossCents,cryptoPendingCents,cryptoReleasedCents,sellers:rows});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status})}}
