import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/firebase-admin";
import { publicError, userFromRequest } from "@/lib/server";
export const runtime="nodejs";export const dynamic="force-dynamic";
const pendingWithdrawalStatuses=new Set(["pending","pending-manual-payment","processing"]);
const paidWithdrawalStatuses=new Set(["paid","completed","processed","paid-out"]);
const releasedOrderStatuses=new Set(["completed-released","released","completed"]);
const pendingOrderStatuses=new Set(["paid","active","in-progress","pending","completed-pending","crypto-received"]);
const cryptoMethods=new Set(["crypto-usdt-trc20","usdt-trc20","usdc-bep20"]);
function cents(...values:unknown[]){for(const value of values){const n=Number(value);if(Number.isFinite(n)&&n!==0)return Math.round(n)}return 0}
function hasConfirmedStripePayment(order:Record<string,unknown>){const intent=String(order.stripePaymentIntent||"").trim();if(!intent)return false;const status=String(order.status||"").toLowerCase();return releasedOrderStatuses.has(status)||pendingOrderStatuses.has(status)}
async function assertAdmin(req:NextRequest){const token=await userFromRequest(req);const email=String(token.email||"").toLowerCase();const allowed=String(process.env.SUPER_ADMIN_EMAIL||process.env.ADMIN_EMAIL||"").toLowerCase();if(!allowed||email!==allowed)throw new Error("FORBIDDEN");return token}
export async function GET(req:NextRequest){try{await assertAdmin(req);const [users,orders,withdrawals]=await Promise.all([db.collection("users").limit(1000).get(),db.collection("orders").limit(5000).get(),db.collection("withdrawals").limit(2000).get()]);const sellers=new Map<string,any>();for(const d of users.docs){const x=d.data() as Record<string,unknown>;sellers.set(d.id,{id:d.id,name:[x.firstName,x.lastName].filter(Boolean).join(" ")||String(x.name||x.displayName||""),email:String(x.email||""),mode:String(x.mode||"BUYING"),totalEarningsCents:0,pendingEarningsCents:0,availableBalanceCents:0,usdtBalanceCents:Number(x.usdtBalanceCents||0),usdcBalanceCents:Number(x.usdcBalanceCents||0),paidWithdrawalsCents:0,pendingWithdrawalsCents:0})}
let grossCents=0,sellerEarningsCents=0,platformFeesCents=0,cryptoGrossCents=0,cryptoPendingCents=0,cryptoReleasedCents=0;
for(const d of orders.docs){const o=d.data() as Record<string,unknown>;const status=String(o.status||"").toLowerCase();const isCrypto=cryptoMethods.has(String(o.paymentMethod||""));if(isCrypto){const gross=cents(o.serviceCents,o.amountCents,o.totalCents),net=cents(o.sellerNetCents,o.sellerEarningsCents,o.netCents)||gross;cryptoGrossCents+=gross;if(status==="crypto-received")cryptoPendingCents+=net;if(releasedOrderStatuses.has(status))cryptoReleasedCents+=net;if(!["crypto-received",...releasedOrderStatuses].includes(status))continue;const sellerId=String(o.sellerId||"");if(!sellerId)continue;if(!sellers.has(sellerId))sellers.set(sellerId,{id:sellerId,name:"",email:"",mode:"SELLER",totalEarningsCents:0,pendingEarningsCents:0,availableBalanceCents:0,usdtBalanceCents:0,usdcBalanceCents:0,paidWithdrawalsCents:0,pendingWithdrawalsCents:0});const seller=sellers.get(sellerId)!;if(status==="crypto-received")seller.pendingEarningsCents+=net;else seller.totalEarningsCents+=net;continue}
if(!hasConfirmedStripePayment(o))continue;const gross=cents(o.serviceCents,o.amountCents,o.totalCents),net=cents(o.sellerNetCents,o.sellerEarningsCents,o.netCents)||gross,fee=cents(o.platformFeeCents,o.feeCents);grossCents+=gross;sellerEarningsCents+=net;platformFeesCents+=fee;const sellerId=String(o.sellerId||"");if(!sellerId)continue;if(!sellers.has(sellerId))sellers.set(sellerId,{id:sellerId,name:"",email:"",mode:"SELLER",totalEarningsCents:0,pendingEarningsCents:0,availableBalanceCents:0,usdtBalanceCents:0,usdcBalanceCents:0,paidWithdrawalsCents:0,pendingWithdrawalsCents:0});const seller=sellers.get(sellerId)!;if(releasedOrderStatuses.has(status))seller.totalEarningsCents+=net;else if(pendingOrderStatuses.has(status))seller.pendingEarningsCents+=net}
let pendingWithdrawalsCents=0,paidWithdrawalsCents=0;for(const d of withdrawals.docs){const w=d.data() as Record<string,unknown>,status=String(w.status||"").toLowerCase(),gross=cents(w.grossCents,w.amountCents,w.netCents),net=cents(w.netCents,w.amountCents,w.grossCents),sellerId=String(w.sellerId||w.userId||"");if(pendingWithdrawalStatuses.has(status))pendingWithdrawalsCents+=net;if(paidWithdrawalStatuses.has(status))paidWithdrawalsCents+=net;if(sellerId&&sellers.has(sellerId)){const seller=sellers.get(sellerId)!;if(pendingWithdrawalStatuses.has(status))seller.pendingWithdrawalsCents+=gross;if(paidWithdrawalStatuses.has(status))seller.paidWithdrawalsCents+=gross}}
const rows=[...sellers.values()].map(s=>({...s,availableBalanceCents:Math.max(0,s.totalEarningsCents-s.paidWithdrawalsCents-s.pendingWithdrawalsCents)})).filter(x=>x.mode==="SELLER"||x.totalEarningsCents>0||x.pendingEarningsCents>0||x.usdtBalanceCents>0||x.usdcBalanceCents>0).sort((a,b)=>b.usdcBalanceCents+b.usdtBalanceCents-a.usdcBalanceCents-a.usdtBalanceCents||b.availableBalanceCents-a.availableBalanceCents);
return NextResponse.json({grossCents,sellerEarningsCents,platformFeesCents,pendingWithdrawalsCents,paidWithdrawalsCents,cryptoGrossCents,cryptoPendingCents,cryptoReleasedCents,sellers:rows});}catch(error){const x=publicError(error);return NextResponse.json({error:x.message},{status:x.status})}}
