import {NextRequest,NextResponse} from "next/server";
import {FieldValue} from "firebase-admin/firestore";
import {z} from "zod";
import {db} from "@/lib/firebase-admin";
import {publicError,userFromRequest} from "@/lib/server";
export const runtime="nodejs";export const dynamic="force-dynamic";
const actionSchema=z.object({invoiceId:z.string().min(1),action:z.enum(["confirm","reject"]),note:z.string().trim().max(1000).default(""),source:z.enum(["invoice","order"]).optional()});
async function assertAdmin(req:NextRequest){const token=await userFromRequest(req);const email=String(token.email||"").toLowerCase(),allowed=String(process.env.SUPER_ADMIN_EMAIL||process.env.ADMIN_EMAIL||"").toLowerCase();if(!allowed||email!==allowed)throw new Error("FORBIDDEN");return token;}
const serial=(x:any,source:"invoice"|"order")=>({id:x.id,...x.data(),source});
export async function GET(req:NextRequest){try{await assertAdmin(req);const [invoices,orders]=await Promise.all([db.collection("customInvoices").where("status","==","payment-submitted").limit(200).get(),db.collection("orders").where("status","==","payment-submitted").limit(200).get()]);return NextResponse.json({payments:[...invoices.docs.map(d=>serial(d,"invoice")),...orders.docs.filter(d=>String(d.data()?.paymentMethod)==="crypto-usdt-trc20").map(d=>serial(d,"order"))]});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PATCH(req:NextRequest){try{const admin=await assertAdmin(req),body=actionSchema.parse(await req.json()),source=body.source||"invoice",collection=source==="order"?"orders":"customInvoices",ref=db.collection(collection).doc(body.invoiceId);let result:any={};await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("NOT_FOUND");const row=snap.data()||{};if(String(row.status)!=="payment-submitted")throw new Error("This payment is no longer awaiting confirmation.");if(body.action==="reject"){tx.set(ref,{status:source==="order"?"payment-rejected":"payment-rejected",adminNote:body.note,reviewedBy:admin.uid,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"reject"};return;}if(source==="order"){tx.set(ref,{status:"paid",paidAt:FieldValue.serverTimestamp(),paymentConfirmedBy:admin.uid,adminNote:body.note,updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"confirm"};return;}const buyerId=String(row.buyerId||""),amountCents=Math.max(0,Math.round(Number(row.amountCents||0)));if(!buyerId||!amountCents)throw new Error("Invalid payment record.");const buyerRef=db.collection("users").doc(buyerId),buyerSnap=await tx.get(buyerRef);if(!buyerSnap.exists)throw new Error("BUYER_NOT_FOUND");const ledgerRef=db.collection("balanceTransactions").doc(body.invoiceId);if(await tx.get(ledgerRef).then(x=>x.exists))throw new Error("This payment has already been credited.");tx.set(buyerRef,{availableBalanceCents:FieldValue.increment(amountCents),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(ledgerRef,{userId:buyerId,type:"crypto-usdt-deposit",amountCents,currency:"USDT",invoiceId:body.invoiceId,txHash:String(row.txHash||""),status:"confirmed",createdAt:FieldValue.serverTimestamp(),confirmedBy:admin.uid});tx.set(ref,{status:"payment-confirmed",balanceCredited:true,adminNote:body.note,reviewedBy:admin.uid,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"confirm"};});return NextResponse.json({ok:true,...result});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
