import {NextRequest,NextResponse} from "next/server";
import {FieldValue} from "firebase-admin/firestore";
import {z} from "zod";
import {db} from "@/lib/firebase-admin";
import {publicError,userFromRequest} from "@/lib/server";
export const runtime="nodejs";export const dynamic="force-dynamic";
const actionSchema=z.object({invoiceId:z.string().min(1),action:z.enum(["confirm","reject","release"]),note:z.string().trim().max(1000).default(""),source:z.enum(["invoice","order"]).optional()});
async function assertAdmin(req:NextRequest){const token=await userFromRequest(req);const email=String(token.email||"").toLowerCase(),allowed=String(process.env.SUPER_ADMIN_EMAIL||process.env.ADMIN_EMAIL||"").toLowerCase();if(!allowed||email!==allowed)throw new Error("FORBIDDEN");return token;}
const serial=(x:any,source:"invoice"|"order")=>({id:x.id,...x.data(),source});
const cryptoMethods=new Set(["crypto-usdt-trc20","usdt-trc20","usdc-bep20"]);
const OPEN_DISPUTE_STATUSES=new Set(["open","pending","active","under-review","disputed"]);
async function hasOpenDispute(orderId:string,row:any){
  const rowStatus=String(row.status||"").toLowerCase();
  const disputeStatus=String(row.disputeStatus||"").toLowerCase();
  if(rowStatus==="disputed"||OPEN_DISPUTE_STATUSES.has(disputeStatus))return true;
  const snap=await db.collection("disputes").where("orderId","==",orderId).limit(20).get().catch(()=>({empty:true,docs:[]} as any));
  return snap.docs.some((d:any)=>OPEN_DISPUTE_STATUSES.has(String(d.data()?.status||"").toLowerCase()));
}
export async function GET(req:NextRequest){try{await assertAdmin(req);const [invoices,ordersPending,ordersReceived]=await Promise.all([
  db.collection("customInvoices").where("status","==","payment-submitted").limit(200).get(),
  db.collection("orders").where("status","==","payment-submitted").limit(200).get(),
  db.collection("orders").where("status","==","crypto-received").limit(200).get()
]);return NextResponse.json({payments:[...invoices.docs.map(d=>serial(d,"invoice")),...ordersPending.docs.filter(d=>cryptoMethods.has(String(d.data()?.paymentMethod||""))).map(d=>serial(d,"order")),...ordersReceived.docs.filter(d=>cryptoMethods.has(String(d.data()?.paymentMethod||""))).map(d=>serial(d,"order"))]});
}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PATCH(req:NextRequest){try{const admin=await assertAdmin(req),body=actionSchema.parse(await req.json()),source=body.source||"invoice",collection=source==="order"?"orders":"customInvoices",ref=db.collection(collection).doc(body.invoiceId);let result:any={};
if(body.action==="release"){
  if(source!=="order")throw new Error("Only crypto service orders can be released here.");
  const snap=await ref.get();if(!snap.exists)throw new Error("NOT_FOUND");const row=snap.data()||{};
  if(!cryptoMethods.has(String(row.paymentMethod||"")))throw new Error("Only crypto service orders can be released here.");
  if(String(row.status)!=="crypto-received")throw new Error("The payment must be marked received first.");
  const releaseAt=row.releaseAfterAt?.toDate?.()||new Date(row.releaseAfterAt||0);if(!(releaseAt instanceof Date)||Number.isNaN(releaseAt.getTime())||releaseAt.getTime()>Date.now())throw new Error("The five-day dispute window has not expired.");
  if(await hasOpenDispute(body.invoiceId,row))throw new Error("This order has an open dispute and cannot be released.");
  await db.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists)throw new Error("NOT_FOUND");const current=fresh.data()||{};if(String(current.status)!=="crypto-received")throw new Error("This order is no longer awaiting release.");const sellerId=String(current.sellerId||"");const net=Math.max(0,Math.round(Number(current.sellerNetCents??current.serviceCents??current.totalCents??0)));if(!sellerId||net<=0)throw new Error("Invalid seller or release amount.");const currency=String(current.paymentCurrency||"USDT").toUpperCase();if(currency!=="USDT"&&currency!=="USDC")throw new Error("Unsupported seller balance currency.");const ledgerRef=db.collection("balanceTransactions").doc(`crypto-release-${body.invoiceId}`);if((await tx.get(ledgerRef)).exists)throw new Error("This order has already been released.");const balanceField=currency==="USDC"?"usdcBalanceCents":"usdtBalanceCents";tx.set(db.collection("users").doc(sellerId),{[balanceField]:FieldValue.increment(net),availableBalanceCents:FieldValue.increment(net),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(ledgerRef,{userId:sellerId,type:"crypto-order-release",amountCents:net,currency,orderId:body.invoiceId,txHash:String(current.txHash||""),status:"released",createdAt:FieldValue.serverTimestamp(),releasedBy:admin.uid});tx.set(ref,{status:"completed-released",releasedAt:FieldValue.serverTimestamp(),releasedBy:admin.uid,releaseNote:body.note,updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"release",sellerId,amountCents:net,currency};});return NextResponse.json({ok:true,...result});
}
await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("NOT_FOUND");const row=snap.data()||{};const status=String(row.status||"");if(status!=="payment-submitted")throw new Error("This payment is no longer awaiting confirmation.");if(body.action==="reject"){tx.set(ref,{status:"payment-rejected",adminNote:body.note,reviewedBy:admin.uid,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"reject"};return;}if(source==="order"){const releaseAfter=new Date(Date.now()+5*24*60*60*1000);tx.set(ref,{status:"crypto-received",cryptoReceivedAt:FieldValue.serverTimestamp(),releaseAfterAt:releaseAfter,paymentConfirmedBy:admin.uid,adminNote:body.note,updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"confirm",status:"crypto-received",releaseAfterAt:releaseAfter.toISOString()};return;}const buyerId=String(row.buyerId||""),amountCents=Math.max(0,Math.round(Number(row.amountCents||0)));if(!buyerId||!amountCents)throw new Error("Invalid payment record.");const buyerRef=db.collection("users").doc(buyerId);if(!(await tx.get(buyerRef)).exists)throw new Error("BUYER_NOT_FOUND");const ledgerRef=db.collection("balanceTransactions").doc(body.invoiceId);if((await tx.get(ledgerRef)).exists)throw new Error("This payment has already been credited.");tx.set(buyerRef,{availableBalanceCents:FieldValue.increment(amountCents),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(ledgerRef,{userId:buyerId,type:"crypto-stablecoin-deposit",amountCents,currency:String(row.paymentCurrency||"USDT"),invoiceId:body.invoiceId,txHash:String(row.txHash||""),status:"confirmed",createdAt:FieldValue.serverTimestamp(),confirmedBy:admin.uid});tx.set(ref,{status:"payment-confirmed",balanceCredited:true,adminNote:body.note,reviewedBy:admin.uid,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});result={action:"confirm"};});return NextResponse.json({ok:true,...result});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
