import {NextRequest,NextResponse} from "next/server";
import {FieldValue} from "firebase-admin/firestore";
import {db} from "@/lib/firebase-admin";
import {publicError,userFromRequest} from "@/lib/server";
import {notifyUser} from "@/lib/notifications";
export const runtime="nodejs";export const dynamic="force-dynamic";
const actionSchema=require("zod").z.object({invoiceId:require("zod").z.string().min(1),action:require("zod").z.enum(["confirm","reject","release"]),note:require("zod").z.string().trim().max(1000).default(""),source:require("zod").z.enum(["invoice","order"]).optional()});
const cryptoMethods=new Set(["crypto-usdt-trc20","usdt-trc20","usdc-bep20"]);
async function assertAdmin(req:NextRequest){const token=await userFromRequest(req),email=String(token.email||"").toLowerCase(),allowed=String(process.env.SUPER_ADMIN_EMAIL||process.env.ADMIN_EMAIL||"").toLowerCase();if(!allowed||email!==allowed)throw new Error("FORBIDDEN");return token;}
const serial=(x:any,source:"invoice"|"order")=>({id:x.id,...x.data(),source});
export async function GET(req:NextRequest){try{await assertAdmin(req);const [invoices,ordersPending,ordersReceived]=await Promise.all([db.collection("customInvoices").where("purpose","==","service-order").limit(500).get(),db.collection("orders").where("status","==","payment-submitted").limit(200).get(),db.collection("orders").where("status","==","crypto-received").limit(200).get()]);return NextResponse.json({payments:[...invoices.docs.filter(d=>["payment-submitted","crypto-received"].includes(String(d.data()?.status||""))).map(d=>serial(d,"invoice")),...ordersPending.docs.filter(d=>cryptoMethods.has(String(d.data()?.paymentMethod||""))).map(d=>serial(d,"order")),...ordersReceived.docs.filter(d=>cryptoMethods.has(String(d.data()?.paymentMethod||""))).map(d=>serial(d,"order"))]});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PATCH(req:NextRequest){try{const admin=await assertAdmin(req),body=actionSchema.parse(await req.json()),source=body.source||"invoice",collection=source==="order"?"orders":"customInvoices",ref=db.collection(collection).doc(body.invoiceId);if(body.action==="reject"){await ref.set({status:"payment-rejected",adminNote:body.note,reviewedBy:admin.uid,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});return NextResponse.json({ok:true,action:"reject"});}if(body.action==="release"){const snap=await ref.get();if(!snap.exists)throw new Error("NOT_FOUND");const row=snap.data()||{};if(String(row.status)!=="crypto-received")throw new Error("The payment must be approved first.");const releaseAt=row.releaseAfterAt?.toDate?.()||new Date(row.releaseAfterAt||0);if(Number.isNaN(releaseAt.getTime())||releaseAt.getTime()>Date.now())throw new Error("The five-day dispute window has not expired.");return await release(ref,body.invoiceId,row,admin.uid,body.note);}const snap=await ref.get();if(!snap.exists)throw new Error("NOT_FOUND");const row=snap.data()||{};if(String(row.status)!=="payment-submitted")throw new Error("This payment is no longer awaiting confirmation.");const releaseAfter=new Date(Date.now()+5*24*60*60*1000);await ref.set({status:"crypto-received",cryptoReceivedAt:FieldValue.serverTimestamp(),releaseAfterAt:releaseAfter,paymentConfirmedBy:admin.uid,adminNote:body.note,updatedAt:FieldValue.serverTimestamp()},{merge:true});if(row.sellerId)await notifyUser({userId:String(row.sellerId),type:"crypto_earning_approved",eventId:body.invoiceId,title:"Crypto earning approved",message:`${String(row.amountCents/100)} ${String(row.paymentCurrency||row.currency||"USDT")} payment approved. Your earning is assigned to your seller account and will be released after the 5-day dispute window.`,link:"/?inbox=1"});return NextResponse.json({ok:true,action:"confirm",sellerId:row.sellerId||null,status:"crypto-received",releaseAfterAt:releaseAfter.toISOString()});}catch(e){const x=publicError(e);return NextResponse.json({error:x.message},{status:x.status});}}
async function release(ref:any,id:string,row:any,adminId:string,note:string){const sellerId=String(row.sellerId||"");const net=Math.max(0,Math.round(Number(row.sellerNetCents??row.serviceCents??row.amountCents??0)));const currency=String(row.paymentCurrency||row.currency||"USDT").toUpperCase();if(!sellerId||net<=0)throw new Error("Invalid seller or release amount.");if(currency!=="USDT"&&currency!=="USDC")throw new Error("Unsupported currency.");const ledgerRef=db.collection("balanceTransactions").doc(`crypto-release-${id}`);await db.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists)throw new Error("NOT_FOUND");if(String(fresh.data()?.status)!=="crypto-received")throw new Error("This earning is no longer awaiting release.");if((await tx.get(ledgerRef)).exists)throw new Error("This earning has already been released.");const balanceField=currency==="USDC"?"usdcBalanceCents":"usdtBalanceCents";tx.set(db.collection("users").doc(sellerId),{[balanceField]:FieldValue.increment(net),availableBalanceCents:FieldValue.increment(net),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.set(ledgerRef,{userId:sellerId,type:"crypto-service-earning",amountCents:net,currency,invoiceId:id,txHash:String(row.txHash||""),status:"released",createdAt:FieldValue.serverTimestamp(),releasedBy:adminId});tx.set(ref,{status:"completed-released",releasedAt:FieldValue.serverTimestamp(),releasedBy:adminId,releaseNote:note,updatedAt:FieldValue.serverTimestamp()},{merge:true});});return NextResponse.json({ok:true,action:"release",sellerId,amountCents:net,currency});}
